/*
User Management API

Testing SponsorshipV2APIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package platform

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/fanscontest/platform-sdk-go"
)

func Test_platform_SponsorshipV2APIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SponsorshipV2APIService CreateContestsByContestIdSponsorships", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contestId string

		resp, httpRes, err := apiClient.SponsorshipV2API.CreateContestsByContestIdSponsorships(context.Background(), contestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SponsorshipV2APIService CreateSponsorshipsByIdAccept", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SponsorshipV2API.CreateSponsorshipsByIdAccept(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SponsorshipV2APIService CreateSponsorshipsByIdReject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SponsorshipV2API.CreateSponsorshipsByIdReject(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SponsorshipV2APIService GetContestsByContestIdSponsorships", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contestId string

		resp, httpRes, err := apiClient.SponsorshipV2API.GetContestsByContestIdSponsorships(context.Background(), contestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
