/*
User Management API

Testing TeamPreferenceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package platform

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/fanscontest/platform-sdk-go"
)

func Test_platform_TeamPreferenceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TeamPreferenceAPIService UpdateTeamPreferenceByTeamSetId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var teamSetId string

		resp, httpRes, err := apiClient.TeamPreferenceAPI.UpdateTeamPreferenceByTeamSetId(context.Background(), teamSetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
