/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// TeamPreferencesAPIService TeamPreferencesAPI service
type TeamPreferencesAPIService service

type ApiUpdateTeamPreferenceByTeamSetIdRequest struct {
	ctx context.Context
	ApiService *TeamPreferencesAPIService
	teamSetId string
	requestUpsertTeamPreferenceRequest *RequestUpsertTeamPreferenceRequest
	xTenantUserId *string
}

// Preference payload
func (r ApiUpdateTeamPreferenceByTeamSetIdRequest) RequestUpsertTeamPreferenceRequest(requestUpsertTeamPreferenceRequest RequestUpsertTeamPreferenceRequest) ApiUpdateTeamPreferenceByTeamSetIdRequest {
	r.requestUpsertTeamPreferenceRequest = &requestUpsertTeamPreferenceRequest
	return r
}

// Acting-as. The tenant&#39;s own identifier for the fan this request is on behalf of. The platform resolves (tenant, X-Tenant-User-Id) to a platform identity. Omit for tenant-level calls.
func (r ApiUpdateTeamPreferenceByTeamSetIdRequest) XTenantUserId(xTenantUserId string) ApiUpdateTeamPreferenceByTeamSetIdRequest {
	r.xTenantUserId = &xTenantUserId
	return r
}

func (r ApiUpdateTeamPreferenceByTeamSetIdRequest) Execute() (*HandlerStatusResponse, *http.Response, error) {
	return r.ApiService.UpdateTeamPreferenceByTeamSetIdExecute(r)
}

/*
UpdateTeamPreferenceByTeamSetId Set the caller's default team for a logical team set

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param teamSetId Team Set ID
 @return ApiUpdateTeamPreferenceByTeamSetIdRequest
*/
func (a *TeamPreferencesAPIService) UpdateTeamPreferenceByTeamSetId(ctx context.Context, teamSetId string) ApiUpdateTeamPreferenceByTeamSetIdRequest {
	return ApiUpdateTeamPreferenceByTeamSetIdRequest{
		ApiService: a,
		ctx: ctx,
		teamSetId: teamSetId,
	}
}

// Execute executes the request
//  @return HandlerStatusResponse
func (a *TeamPreferencesAPIService) UpdateTeamPreferenceByTeamSetIdExecute(r ApiUpdateTeamPreferenceByTeamSetIdRequest) (*HandlerStatusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *HandlerStatusResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamPreferencesAPIService.UpdateTeamPreferenceByTeamSetId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v2/team-preference/{teamSetId}"
	localVarPath = strings.Replace(localVarPath, "{"+"teamSetId"+"}", url.PathEscape(parameterValueToString(r.teamSetId, "teamSetId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestUpsertTeamPreferenceRequest == nil {
		return localVarReturnValue, nil, reportError("requestUpsertTeamPreferenceRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xTenantUserId != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Tenant-User-Id", r.xTenantUserId, "simple", "")
	}
	// body params
	localVarPostBody = r.requestUpsertTeamPreferenceRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v HandlerErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HandlerErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v HandlerErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
