/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainJurorScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainJurorScore{}

// DomainJurorScore struct for DomainJurorScore
type DomainJurorScore struct {
	EntryId *string `json:"entry_id,omitempty"`
	Id *string `json:"id,omitempty"`
	JurorId *string `json:"juror_id,omitempty"`
	// nullable, tracks edits
	LastEditedAt *string `json:"last_edited_at,omitempty"`
	// 1-5
	Score *int32 `json:"score,omitempty"`
	ScoredAt *string `json:"scored_at,omitempty"`
}

// NewDomainJurorScore instantiates a new DomainJurorScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainJurorScore() *DomainJurorScore {
	this := DomainJurorScore{}
	return &this
}

// NewDomainJurorScoreWithDefaults instantiates a new DomainJurorScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainJurorScoreWithDefaults() *DomainJurorScore {
	this := DomainJurorScore{}
	return &this
}

// GetEntryId returns the EntryId field value if set, zero value otherwise.
func (o *DomainJurorScore) GetEntryId() string {
	if o == nil || IsNil(o.EntryId) {
		var ret string
		return ret
	}
	return *o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetEntryIdOk() (*string, bool) {
	if o == nil || IsNil(o.EntryId) {
		return nil, false
	}
	return o.EntryId, true
}

// HasEntryId returns a boolean if a field has been set.
func (o *DomainJurorScore) HasEntryId() bool {
	if o != nil && !IsNil(o.EntryId) {
		return true
	}

	return false
}

// SetEntryId gets a reference to the given string and assigns it to the EntryId field.
func (o *DomainJurorScore) SetEntryId(v string) {
	o.EntryId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DomainJurorScore) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DomainJurorScore) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DomainJurorScore) SetId(v string) {
	o.Id = &v
}

// GetJurorId returns the JurorId field value if set, zero value otherwise.
func (o *DomainJurorScore) GetJurorId() string {
	if o == nil || IsNil(o.JurorId) {
		var ret string
		return ret
	}
	return *o.JurorId
}

// GetJurorIdOk returns a tuple with the JurorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetJurorIdOk() (*string, bool) {
	if o == nil || IsNil(o.JurorId) {
		return nil, false
	}
	return o.JurorId, true
}

// HasJurorId returns a boolean if a field has been set.
func (o *DomainJurorScore) HasJurorId() bool {
	if o != nil && !IsNil(o.JurorId) {
		return true
	}

	return false
}

// SetJurorId gets a reference to the given string and assigns it to the JurorId field.
func (o *DomainJurorScore) SetJurorId(v string) {
	o.JurorId = &v
}

// GetLastEditedAt returns the LastEditedAt field value if set, zero value otherwise.
func (o *DomainJurorScore) GetLastEditedAt() string {
	if o == nil || IsNil(o.LastEditedAt) {
		var ret string
		return ret
	}
	return *o.LastEditedAt
}

// GetLastEditedAtOk returns a tuple with the LastEditedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetLastEditedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastEditedAt) {
		return nil, false
	}
	return o.LastEditedAt, true
}

// HasLastEditedAt returns a boolean if a field has been set.
func (o *DomainJurorScore) HasLastEditedAt() bool {
	if o != nil && !IsNil(o.LastEditedAt) {
		return true
	}

	return false
}

// SetLastEditedAt gets a reference to the given string and assigns it to the LastEditedAt field.
func (o *DomainJurorScore) SetLastEditedAt(v string) {
	o.LastEditedAt = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *DomainJurorScore) GetScore() int32 {
	if o == nil || IsNil(o.Score) {
		var ret int32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *DomainJurorScore) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given int32 and assigns it to the Score field.
func (o *DomainJurorScore) SetScore(v int32) {
	o.Score = &v
}

// GetScoredAt returns the ScoredAt field value if set, zero value otherwise.
func (o *DomainJurorScore) GetScoredAt() string {
	if o == nil || IsNil(o.ScoredAt) {
		var ret string
		return ret
	}
	return *o.ScoredAt
}

// GetScoredAtOk returns a tuple with the ScoredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorScore) GetScoredAtOk() (*string, bool) {
	if o == nil || IsNil(o.ScoredAt) {
		return nil, false
	}
	return o.ScoredAt, true
}

// HasScoredAt returns a boolean if a field has been set.
func (o *DomainJurorScore) HasScoredAt() bool {
	if o != nil && !IsNil(o.ScoredAt) {
		return true
	}

	return false
}

// SetScoredAt gets a reference to the given string and assigns it to the ScoredAt field.
func (o *DomainJurorScore) SetScoredAt(v string) {
	o.ScoredAt = &v
}

func (o DomainJurorScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainJurorScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EntryId) {
		toSerialize["entry_id"] = o.EntryId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JurorId) {
		toSerialize["juror_id"] = o.JurorId
	}
	if !IsNil(o.LastEditedAt) {
		toSerialize["last_edited_at"] = o.LastEditedAt
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.ScoredAt) {
		toSerialize["scored_at"] = o.ScoredAt
	}
	return toSerialize, nil
}

type NullableDomainJurorScore struct {
	value *DomainJurorScore
	isSet bool
}

func (v NullableDomainJurorScore) Get() *DomainJurorScore {
	return v.value
}

func (v *NullableDomainJurorScore) Set(val *DomainJurorScore) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainJurorScore) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainJurorScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainJurorScore(val *DomainJurorScore) *NullableDomainJurorScore {
	return &NullableDomainJurorScore{value: val, isSet: true}
}

func (v NullableDomainJurorScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainJurorScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


