/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainTimePenaltyConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainTimePenaltyConfiguration{}

// DomainTimePenaltyConfiguration struct for DomainTimePenaltyConfiguration
type DomainTimePenaltyConfiguration struct {
	Color *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
	Reduction *string `json:"reduction,omitempty"`
	Zone *string `json:"zone,omitempty"`
}

// NewDomainTimePenaltyConfiguration instantiates a new DomainTimePenaltyConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainTimePenaltyConfiguration() *DomainTimePenaltyConfiguration {
	this := DomainTimePenaltyConfiguration{}
	return &this
}

// NewDomainTimePenaltyConfigurationWithDefaults instantiates a new DomainTimePenaltyConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainTimePenaltyConfigurationWithDefaults() *DomainTimePenaltyConfiguration {
	this := DomainTimePenaltyConfiguration{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *DomainTimePenaltyConfiguration) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTimePenaltyConfiguration) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *DomainTimePenaltyConfiguration) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *DomainTimePenaltyConfiguration) SetColor(v string) {
	o.Color = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DomainTimePenaltyConfiguration) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTimePenaltyConfiguration) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DomainTimePenaltyConfiguration) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DomainTimePenaltyConfiguration) SetDescription(v string) {
	o.Description = &v
}

// GetReduction returns the Reduction field value if set, zero value otherwise.
func (o *DomainTimePenaltyConfiguration) GetReduction() string {
	if o == nil || IsNil(o.Reduction) {
		var ret string
		return ret
	}
	return *o.Reduction
}

// GetReductionOk returns a tuple with the Reduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTimePenaltyConfiguration) GetReductionOk() (*string, bool) {
	if o == nil || IsNil(o.Reduction) {
		return nil, false
	}
	return o.Reduction, true
}

// HasReduction returns a boolean if a field has been set.
func (o *DomainTimePenaltyConfiguration) HasReduction() bool {
	if o != nil && !IsNil(o.Reduction) {
		return true
	}

	return false
}

// SetReduction gets a reference to the given string and assigns it to the Reduction field.
func (o *DomainTimePenaltyConfiguration) SetReduction(v string) {
	o.Reduction = &v
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *DomainTimePenaltyConfiguration) GetZone() string {
	if o == nil || IsNil(o.Zone) {
		var ret string
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainTimePenaltyConfiguration) GetZoneOk() (*string, bool) {
	if o == nil || IsNil(o.Zone) {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *DomainTimePenaltyConfiguration) HasZone() bool {
	if o != nil && !IsNil(o.Zone) {
		return true
	}

	return false
}

// SetZone gets a reference to the given string and assigns it to the Zone field.
func (o *DomainTimePenaltyConfiguration) SetZone(v string) {
	o.Zone = &v
}

func (o DomainTimePenaltyConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainTimePenaltyConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Reduction) {
		toSerialize["reduction"] = o.Reduction
	}
	if !IsNil(o.Zone) {
		toSerialize["zone"] = o.Zone
	}
	return toSerialize, nil
}

type NullableDomainTimePenaltyConfiguration struct {
	value *DomainTimePenaltyConfiguration
	isSet bool
}

func (v NullableDomainTimePenaltyConfiguration) Get() *DomainTimePenaltyConfiguration {
	return v.value
}

func (v *NullableDomainTimePenaltyConfiguration) Set(val *DomainTimePenaltyConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainTimePenaltyConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainTimePenaltyConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainTimePenaltyConfiguration(val *DomainTimePenaltyConfiguration) *NullableDomainTimePenaltyConfiguration {
	return &NullableDomainTimePenaltyConfiguration{value: val, isSet: true}
}

func (v NullableDomainTimePenaltyConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainTimePenaltyConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


