/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerCreatePlatformRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerCreatePlatformRequest{}

// HandlerCreatePlatformRequest struct for HandlerCreatePlatformRequest
type HandlerCreatePlatformRequest struct {
	Name string `json:"name"`
}

type _HandlerCreatePlatformRequest HandlerCreatePlatformRequest

// NewHandlerCreatePlatformRequest instantiates a new HandlerCreatePlatformRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerCreatePlatformRequest(name string) *HandlerCreatePlatformRequest {
	this := HandlerCreatePlatformRequest{}
	this.Name = name
	return &this
}

// NewHandlerCreatePlatformRequestWithDefaults instantiates a new HandlerCreatePlatformRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerCreatePlatformRequestWithDefaults() *HandlerCreatePlatformRequest {
	this := HandlerCreatePlatformRequest{}
	return &this
}

// GetName returns the Name field value
func (o *HandlerCreatePlatformRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HandlerCreatePlatformRequest) SetName(v string) {
	o.Name = v
}

func (o HandlerCreatePlatformRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerCreatePlatformRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *HandlerCreatePlatformRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerCreatePlatformRequest := _HandlerCreatePlatformRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerCreatePlatformRequest)

	if err != nil {
		return err
	}

	*o = HandlerCreatePlatformRequest(varHandlerCreatePlatformRequest)

	return err
}

type NullableHandlerCreatePlatformRequest struct {
	value *HandlerCreatePlatformRequest
	isSet bool
}

func (v NullableHandlerCreatePlatformRequest) Get() *HandlerCreatePlatformRequest {
	return v.value
}

func (v *NullableHandlerCreatePlatformRequest) Set(val *HandlerCreatePlatformRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerCreatePlatformRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerCreatePlatformRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerCreatePlatformRequest(val *HandlerCreatePlatformRequest) *NullableHandlerCreatePlatformRequest {
	return &NullableHandlerCreatePlatformRequest{value: val, isSet: true}
}

func (v NullableHandlerCreatePlatformRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerCreatePlatformRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


