/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainJurorAssignmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainJurorAssignmentResponse{}

// DomainJurorAssignmentResponse struct for DomainJurorAssignmentResponse
type DomainJurorAssignmentResponse struct {
	Data DomainJurorAssignment `json:"data"`
}

type _DomainJurorAssignmentResponse DomainJurorAssignmentResponse

// NewDomainJurorAssignmentResponse instantiates a new DomainJurorAssignmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainJurorAssignmentResponse(data DomainJurorAssignment) *DomainJurorAssignmentResponse {
	this := DomainJurorAssignmentResponse{}
	this.Data = data
	return &this
}

// NewDomainJurorAssignmentResponseWithDefaults instantiates a new DomainJurorAssignmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainJurorAssignmentResponseWithDefaults() *DomainJurorAssignmentResponse {
	this := DomainJurorAssignmentResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainJurorAssignmentResponse) GetData() DomainJurorAssignment {
	if o == nil {
		var ret DomainJurorAssignment
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainJurorAssignmentResponse) GetDataOk() (*DomainJurorAssignment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DomainJurorAssignmentResponse) SetData(v DomainJurorAssignment) {
	o.Data = v
}

func (o DomainJurorAssignmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainJurorAssignmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DomainJurorAssignmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainJurorAssignmentResponse := _DomainJurorAssignmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainJurorAssignmentResponse)

	if err != nil {
		return err
	}

	*o = DomainJurorAssignmentResponse(varDomainJurorAssignmentResponse)

	return err
}

type NullableDomainJurorAssignmentResponse struct {
	value *DomainJurorAssignmentResponse
	isSet bool
}

func (v NullableDomainJurorAssignmentResponse) Get() *DomainJurorAssignmentResponse {
	return v.value
}

func (v *NullableDomainJurorAssignmentResponse) Set(val *DomainJurorAssignmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainJurorAssignmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainJurorAssignmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainJurorAssignmentResponse(val *DomainJurorAssignmentResponse) *NullableDomainJurorAssignmentResponse {
	return &NullableDomainJurorAssignmentResponse{value: val, isSet: true}
}

func (v NullableDomainJurorAssignmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainJurorAssignmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


