/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerOGScoreboardDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerOGScoreboardDataResponse{}

// HandlerOGScoreboardDataResponse struct for HandlerOGScoreboardDataResponse
type HandlerOGScoreboardDataResponse struct {
	Data HandlerOGScoreboardData `json:"data"`
}

type _HandlerOGScoreboardDataResponse HandlerOGScoreboardDataResponse

// NewHandlerOGScoreboardDataResponse instantiates a new HandlerOGScoreboardDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerOGScoreboardDataResponse(data HandlerOGScoreboardData) *HandlerOGScoreboardDataResponse {
	this := HandlerOGScoreboardDataResponse{}
	this.Data = data
	return &this
}

// NewHandlerOGScoreboardDataResponseWithDefaults instantiates a new HandlerOGScoreboardDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerOGScoreboardDataResponseWithDefaults() *HandlerOGScoreboardDataResponse {
	this := HandlerOGScoreboardDataResponse{}
	return &this
}

// GetData returns the Data field value
func (o *HandlerOGScoreboardDataResponse) GetData() HandlerOGScoreboardData {
	if o == nil {
		var ret HandlerOGScoreboardData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *HandlerOGScoreboardDataResponse) GetDataOk() (*HandlerOGScoreboardData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *HandlerOGScoreboardDataResponse) SetData(v HandlerOGScoreboardData) {
	o.Data = v
}

func (o HandlerOGScoreboardDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerOGScoreboardDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *HandlerOGScoreboardDataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerOGScoreboardDataResponse := _HandlerOGScoreboardDataResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerOGScoreboardDataResponse)

	if err != nil {
		return err
	}

	*o = HandlerOGScoreboardDataResponse(varHandlerOGScoreboardDataResponse)

	return err
}

type NullableHandlerOGScoreboardDataResponse struct {
	value *HandlerOGScoreboardDataResponse
	isSet bool
}

func (v NullableHandlerOGScoreboardDataResponse) Get() *HandlerOGScoreboardDataResponse {
	return v.value
}

func (v *NullableHandlerOGScoreboardDataResponse) Set(val *HandlerOGScoreboardDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerOGScoreboardDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerOGScoreboardDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerOGScoreboardDataResponse(val *HandlerOGScoreboardDataResponse) *NullableHandlerOGScoreboardDataResponse {
	return &NullableHandlerOGScoreboardDataResponse{value: val, isSet: true}
}

func (v NullableHandlerOGScoreboardDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerOGScoreboardDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


