/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSponsorshipPackagesByIdAgreement200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSponsorshipPackagesByIdAgreement200Response{}

// GetSponsorshipPackagesByIdAgreement200Response struct for GetSponsorshipPackagesByIdAgreement200Response
type GetSponsorshipPackagesByIdAgreement200Response struct {
	Data DomainSponsorshipPackageAgreement `json:"data"`
}

type _GetSponsorshipPackagesByIdAgreement200Response GetSponsorshipPackagesByIdAgreement200Response

// NewGetSponsorshipPackagesByIdAgreement200Response instantiates a new GetSponsorshipPackagesByIdAgreement200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSponsorshipPackagesByIdAgreement200Response(data DomainSponsorshipPackageAgreement) *GetSponsorshipPackagesByIdAgreement200Response {
	this := GetSponsorshipPackagesByIdAgreement200Response{}
	this.Data = data
	return &this
}

// NewGetSponsorshipPackagesByIdAgreement200ResponseWithDefaults instantiates a new GetSponsorshipPackagesByIdAgreement200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSponsorshipPackagesByIdAgreement200ResponseWithDefaults() *GetSponsorshipPackagesByIdAgreement200Response {
	this := GetSponsorshipPackagesByIdAgreement200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetSponsorshipPackagesByIdAgreement200Response) GetData() DomainSponsorshipPackageAgreement {
	if o == nil {
		var ret DomainSponsorshipPackageAgreement
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetSponsorshipPackagesByIdAgreement200Response) GetDataOk() (*DomainSponsorshipPackageAgreement, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetSponsorshipPackagesByIdAgreement200Response) SetData(v DomainSponsorshipPackageAgreement) {
	o.Data = v
}

func (o GetSponsorshipPackagesByIdAgreement200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSponsorshipPackagesByIdAgreement200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetSponsorshipPackagesByIdAgreement200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSponsorshipPackagesByIdAgreement200Response := _GetSponsorshipPackagesByIdAgreement200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSponsorshipPackagesByIdAgreement200Response)

	if err != nil {
		return err
	}

	*o = GetSponsorshipPackagesByIdAgreement200Response(varGetSponsorshipPackagesByIdAgreement200Response)

	return err
}

type NullableGetSponsorshipPackagesByIdAgreement200Response struct {
	value *GetSponsorshipPackagesByIdAgreement200Response
	isSet bool
}

func (v NullableGetSponsorshipPackagesByIdAgreement200Response) Get() *GetSponsorshipPackagesByIdAgreement200Response {
	return v.value
}

func (v *NullableGetSponsorshipPackagesByIdAgreement200Response) Set(val *GetSponsorshipPackagesByIdAgreement200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSponsorshipPackagesByIdAgreement200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSponsorshipPackagesByIdAgreement200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSponsorshipPackagesByIdAgreement200Response(val *GetSponsorshipPackagesByIdAgreement200Response) *NullableGetSponsorshipPackagesByIdAgreement200Response {
	return &NullableGetSponsorshipPackagesByIdAgreement200Response{value: val, isSet: true}
}

func (v NullableGetSponsorshipPackagesByIdAgreement200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSponsorshipPackagesByIdAgreement200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


