/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainStats{}

// DomainStats struct for DomainStats
type DomainStats struct {
	ContestsCount *int32 `json:"contests_count,omitempty"`
	SubscribersCount *int32 `json:"subscribers_count,omitempty"`
}

// NewDomainStats instantiates a new DomainStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainStats() *DomainStats {
	this := DomainStats{}
	return &this
}

// NewDomainStatsWithDefaults instantiates a new DomainStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainStatsWithDefaults() *DomainStats {
	this := DomainStats{}
	return &this
}

// GetContestsCount returns the ContestsCount field value if set, zero value otherwise.
func (o *DomainStats) GetContestsCount() int32 {
	if o == nil || IsNil(o.ContestsCount) {
		var ret int32
		return ret
	}
	return *o.ContestsCount
}

// GetContestsCountOk returns a tuple with the ContestsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainStats) GetContestsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ContestsCount) {
		return nil, false
	}
	return o.ContestsCount, true
}

// HasContestsCount returns a boolean if a field has been set.
func (o *DomainStats) HasContestsCount() bool {
	if o != nil && !IsNil(o.ContestsCount) {
		return true
	}

	return false
}

// SetContestsCount gets a reference to the given int32 and assigns it to the ContestsCount field.
func (o *DomainStats) SetContestsCount(v int32) {
	o.ContestsCount = &v
}

// GetSubscribersCount returns the SubscribersCount field value if set, zero value otherwise.
func (o *DomainStats) GetSubscribersCount() int32 {
	if o == nil || IsNil(o.SubscribersCount) {
		var ret int32
		return ret
	}
	return *o.SubscribersCount
}

// GetSubscribersCountOk returns a tuple with the SubscribersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainStats) GetSubscribersCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SubscribersCount) {
		return nil, false
	}
	return o.SubscribersCount, true
}

// HasSubscribersCount returns a boolean if a field has been set.
func (o *DomainStats) HasSubscribersCount() bool {
	if o != nil && !IsNil(o.SubscribersCount) {
		return true
	}

	return false
}

// SetSubscribersCount gets a reference to the given int32 and assigns it to the SubscribersCount field.
func (o *DomainStats) SetSubscribersCount(v int32) {
	o.SubscribersCount = &v
}

func (o DomainStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContestsCount) {
		toSerialize["contests_count"] = o.ContestsCount
	}
	if !IsNil(o.SubscribersCount) {
		toSerialize["subscribers_count"] = o.SubscribersCount
	}
	return toSerialize, nil
}

type NullableDomainStats struct {
	value *DomainStats
	isSet bool
}

func (v NullableDomainStats) Get() *DomainStats {
	return v.value
}

func (v *NullableDomainStats) Set(val *DomainStats) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainStats) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainStats(val *DomainStats) *NullableDomainStats {
	return &NullableDomainStats{value: val, isSet: true}
}

func (v NullableDomainStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


