/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainIntervalOccurrence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainIntervalOccurrence{}

// DomainIntervalOccurrence struct for DomainIntervalOccurrence
type DomainIntervalOccurrence struct {
	Monthly *int32 `json:"monthly,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Weekly *int32 `json:"weekly,omitempty"`
}

// NewDomainIntervalOccurrence instantiates a new DomainIntervalOccurrence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainIntervalOccurrence() *DomainIntervalOccurrence {
	this := DomainIntervalOccurrence{}
	return &this
}

// NewDomainIntervalOccurrenceWithDefaults instantiates a new DomainIntervalOccurrence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainIntervalOccurrenceWithDefaults() *DomainIntervalOccurrence {
	this := DomainIntervalOccurrence{}
	return &this
}

// GetMonthly returns the Monthly field value if set, zero value otherwise.
func (o *DomainIntervalOccurrence) GetMonthly() int32 {
	if o == nil || IsNil(o.Monthly) {
		var ret int32
		return ret
	}
	return *o.Monthly
}

// GetMonthlyOk returns a tuple with the Monthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainIntervalOccurrence) GetMonthlyOk() (*int32, bool) {
	if o == nil || IsNil(o.Monthly) {
		return nil, false
	}
	return o.Monthly, true
}

// HasMonthly returns a boolean if a field has been set.
func (o *DomainIntervalOccurrence) HasMonthly() bool {
	if o != nil && !IsNil(o.Monthly) {
		return true
	}

	return false
}

// SetMonthly gets a reference to the given int32 and assigns it to the Monthly field.
func (o *DomainIntervalOccurrence) SetMonthly(v int32) {
	o.Monthly = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *DomainIntervalOccurrence) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainIntervalOccurrence) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *DomainIntervalOccurrence) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *DomainIntervalOccurrence) SetTotal(v int32) {
	o.Total = &v
}

// GetWeekly returns the Weekly field value if set, zero value otherwise.
func (o *DomainIntervalOccurrence) GetWeekly() int32 {
	if o == nil || IsNil(o.Weekly) {
		var ret int32
		return ret
	}
	return *o.Weekly
}

// GetWeeklyOk returns a tuple with the Weekly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainIntervalOccurrence) GetWeeklyOk() (*int32, bool) {
	if o == nil || IsNil(o.Weekly) {
		return nil, false
	}
	return o.Weekly, true
}

// HasWeekly returns a boolean if a field has been set.
func (o *DomainIntervalOccurrence) HasWeekly() bool {
	if o != nil && !IsNil(o.Weekly) {
		return true
	}

	return false
}

// SetWeekly gets a reference to the given int32 and assigns it to the Weekly field.
func (o *DomainIntervalOccurrence) SetWeekly(v int32) {
	o.Weekly = &v
}

func (o DomainIntervalOccurrence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainIntervalOccurrence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Monthly) {
		toSerialize["monthly"] = o.Monthly
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Weekly) {
		toSerialize["weekly"] = o.Weekly
	}
	return toSerialize, nil
}

type NullableDomainIntervalOccurrence struct {
	value *DomainIntervalOccurrence
	isSet bool
}

func (v NullableDomainIntervalOccurrence) Get() *DomainIntervalOccurrence {
	return v.value
}

func (v *NullableDomainIntervalOccurrence) Set(val *DomainIntervalOccurrence) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainIntervalOccurrence) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainIntervalOccurrence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainIntervalOccurrence(val *DomainIntervalOccurrence) *NullableDomainIntervalOccurrence {
	return &NullableDomainIntervalOccurrence{value: val, isSet: true}
}

func (v NullableDomainIntervalOccurrence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainIntervalOccurrence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


