/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetChannelsByIdSubscriptions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChannelsByIdSubscriptions200Response{}

// GetChannelsByIdSubscriptions200Response struct for GetChannelsByIdSubscriptions200Response
type GetChannelsByIdSubscriptions200Response struct {
	Data []DomainSubscription `json:"data"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

type _GetChannelsByIdSubscriptions200Response GetChannelsByIdSubscriptions200Response

// NewGetChannelsByIdSubscriptions200Response instantiates a new GetChannelsByIdSubscriptions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChannelsByIdSubscriptions200Response(data []DomainSubscription) *GetChannelsByIdSubscriptions200Response {
	this := GetChannelsByIdSubscriptions200Response{}
	this.Data = data
	return &this
}

// NewGetChannelsByIdSubscriptions200ResponseWithDefaults instantiates a new GetChannelsByIdSubscriptions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChannelsByIdSubscriptions200ResponseWithDefaults() *GetChannelsByIdSubscriptions200Response {
	this := GetChannelsByIdSubscriptions200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetChannelsByIdSubscriptions200Response) GetData() []DomainSubscription {
	if o == nil {
		var ret []DomainSubscription
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetChannelsByIdSubscriptions200Response) GetDataOk() ([]DomainSubscription, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetChannelsByIdSubscriptions200Response) SetData(v []DomainSubscription) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GetChannelsByIdSubscriptions200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChannelsByIdSubscriptions200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GetChannelsByIdSubscriptions200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *GetChannelsByIdSubscriptions200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o GetChannelsByIdSubscriptions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChannelsByIdSubscriptions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

func (o *GetChannelsByIdSubscriptions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetChannelsByIdSubscriptions200Response := _GetChannelsByIdSubscriptions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetChannelsByIdSubscriptions200Response)

	if err != nil {
		return err
	}

	*o = GetChannelsByIdSubscriptions200Response(varGetChannelsByIdSubscriptions200Response)

	return err
}

type NullableGetChannelsByIdSubscriptions200Response struct {
	value *GetChannelsByIdSubscriptions200Response
	isSet bool
}

func (v NullableGetChannelsByIdSubscriptions200Response) Get() *GetChannelsByIdSubscriptions200Response {
	return v.value
}

func (v *NullableGetChannelsByIdSubscriptions200Response) Set(val *GetChannelsByIdSubscriptions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChannelsByIdSubscriptions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChannelsByIdSubscriptions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChannelsByIdSubscriptions200Response(val *GetChannelsByIdSubscriptions200Response) *NullableGetChannelsByIdSubscriptions200Response {
	return &NullableGetChannelsByIdSubscriptions200Response{value: val, isSet: true}
}

func (v NullableGetChannelsByIdSubscriptions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChannelsByIdSubscriptions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


