/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateContestsByIdEnrollment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContestsByIdEnrollment200Response{}

// CreateContestsByIdEnrollment200Response struct for CreateContestsByIdEnrollment200Response
type CreateContestsByIdEnrollment200Response struct {
	Data DomainParticipation `json:"data"`
}

type _CreateContestsByIdEnrollment200Response CreateContestsByIdEnrollment200Response

// NewCreateContestsByIdEnrollment200Response instantiates a new CreateContestsByIdEnrollment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContestsByIdEnrollment200Response(data DomainParticipation) *CreateContestsByIdEnrollment200Response {
	this := CreateContestsByIdEnrollment200Response{}
	this.Data = data
	return &this
}

// NewCreateContestsByIdEnrollment200ResponseWithDefaults instantiates a new CreateContestsByIdEnrollment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContestsByIdEnrollment200ResponseWithDefaults() *CreateContestsByIdEnrollment200Response {
	this := CreateContestsByIdEnrollment200Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateContestsByIdEnrollment200Response) GetData() DomainParticipation {
	if o == nil {
		var ret DomainParticipation
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateContestsByIdEnrollment200Response) GetDataOk() (*DomainParticipation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateContestsByIdEnrollment200Response) SetData(v DomainParticipation) {
	o.Data = v
}

func (o CreateContestsByIdEnrollment200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContestsByIdEnrollment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateContestsByIdEnrollment200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateContestsByIdEnrollment200Response := _CreateContestsByIdEnrollment200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateContestsByIdEnrollment200Response)

	if err != nil {
		return err
	}

	*o = CreateContestsByIdEnrollment200Response(varCreateContestsByIdEnrollment200Response)

	return err
}

type NullableCreateContestsByIdEnrollment200Response struct {
	value *CreateContestsByIdEnrollment200Response
	isSet bool
}

func (v NullableCreateContestsByIdEnrollment200Response) Get() *CreateContestsByIdEnrollment200Response {
	return v.value
}

func (v *NullableCreateContestsByIdEnrollment200Response) Set(val *CreateContestsByIdEnrollment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContestsByIdEnrollment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContestsByIdEnrollment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContestsByIdEnrollment200Response(val *CreateContestsByIdEnrollment200Response) *NullableCreateContestsByIdEnrollment200Response {
	return &NullableCreateContestsByIdEnrollment200Response{value: val, isSet: true}
}

func (v NullableCreateContestsByIdEnrollment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContestsByIdEnrollment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


