/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestUpdateContestHeaderImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestUpdateContestHeaderImage{}

// RequestUpdateContestHeaderImage struct for RequestUpdateContestHeaderImage
type RequestUpdateContestHeaderImage struct {
	HeaderImageUrl string `json:"header_image_url"`
}

type _RequestUpdateContestHeaderImage RequestUpdateContestHeaderImage

// NewRequestUpdateContestHeaderImage instantiates a new RequestUpdateContestHeaderImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestUpdateContestHeaderImage(headerImageUrl string) *RequestUpdateContestHeaderImage {
	this := RequestUpdateContestHeaderImage{}
	this.HeaderImageUrl = headerImageUrl
	return &this
}

// NewRequestUpdateContestHeaderImageWithDefaults instantiates a new RequestUpdateContestHeaderImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestUpdateContestHeaderImageWithDefaults() *RequestUpdateContestHeaderImage {
	this := RequestUpdateContestHeaderImage{}
	return &this
}

// GetHeaderImageUrl returns the HeaderImageUrl field value
func (o *RequestUpdateContestHeaderImage) GetHeaderImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HeaderImageUrl
}

// GetHeaderImageUrlOk returns a tuple with the HeaderImageUrl field value
// and a boolean to check if the value has been set.
func (o *RequestUpdateContestHeaderImage) GetHeaderImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeaderImageUrl, true
}

// SetHeaderImageUrl sets field value
func (o *RequestUpdateContestHeaderImage) SetHeaderImageUrl(v string) {
	o.HeaderImageUrl = v
}

func (o RequestUpdateContestHeaderImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestUpdateContestHeaderImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["header_image_url"] = o.HeaderImageUrl
	return toSerialize, nil
}

func (o *RequestUpdateContestHeaderImage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"header_image_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestUpdateContestHeaderImage := _RequestUpdateContestHeaderImage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestUpdateContestHeaderImage)

	if err != nil {
		return err
	}

	*o = RequestUpdateContestHeaderImage(varRequestUpdateContestHeaderImage)

	return err
}

type NullableRequestUpdateContestHeaderImage struct {
	value *RequestUpdateContestHeaderImage
	isSet bool
}

func (v NullableRequestUpdateContestHeaderImage) Get() *RequestUpdateContestHeaderImage {
	return v.value
}

func (v *NullableRequestUpdateContestHeaderImage) Set(val *RequestUpdateContestHeaderImage) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestUpdateContestHeaderImage) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestUpdateContestHeaderImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestUpdateContestHeaderImage(val *RequestUpdateContestHeaderImage) *NullableRequestUpdateContestHeaderImage {
	return &NullableRequestUpdateContestHeaderImage{value: val, isSet: true}
}

func (v NullableRequestUpdateContestHeaderImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestUpdateContestHeaderImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


