/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainContest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainContest{}

// DomainContest struct for DomainContest
type DomainContest struct {
	// Required for creative contests
	Category *string `json:"category,omitempty"`
	Channel *DomainChannel `json:"channel,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Description *string `json:"description,omitempty"`
	Difficulty *string `json:"difficulty,omitempty"`
	// Default: 0
	ExtensionCount *int32 `json:"extension_count,omitempty"`
	// @deprecated
	FairPlayGrouping *bool `json:"fair_play_grouping,omitempty"`
	// 'system' or 'open'
	GroupingType *string `json:"grouping_type,omitempty"`
	HeaderImageUrl *string `json:"header_image_url,omitempty"`
	Id *string `json:"id,omitempty"`
	// Calculated: EndAt + 7 days
	JudgingDeadline *string `json:"judging_deadline,omitempty"`
	// Use JurorSelectionModeRandom, JurorSelectionModeInvited, or JurorSelectionModeHybrid
	JurorSelectionMode *string `json:"juror_selection_mode,omitempty"`
	// Default: 5
	JurySize *int32 `json:"jury_size,omitempty"`
	MemberParticipation *DomainMemberParticipationSummary `json:"member_participation,omitempty"`
	// Default: 3
	MinJurorScores *int32 `json:"min_juror_scores,omitempty"`
	NoOfGroups *int32 `json:"no_of_groups,omitempty"`
	NoOfPuzzles *int32 `json:"no_of_puzzles,omitempty"`
	// @deprecated
	NoOfWinners *int32 `json:"no_of_winners,omitempty"`
	ParticipationRules *DomainParticipationRules `json:"participation_rules,omitempty"`
	// v1; prefer source_id
	PuzzleSheetId *string `json:"puzzle_sheet_id,omitempty"`
	// v1; prefer source_type
	QuestionType *DomainContestType `json:"question_type,omitempty"`
	Reward *DomainReward `json:"reward,omitempty"`
	Sender *DomainPlatformIdentity `json:"sender,omitempty"`
	// v2; same as puzzle_sheet_id
	SourceId *string `json:"source_id,omitempty"`
	// v2; same as question_type
	SourceType *DomainContestType `json:"source_type,omitempty"`
	// Only present if contest has accepted sponsorship
	Sponsor *DomainSponsorInfo `json:"sponsor,omitempty"`
	State *string `json:"state,omitempty"`
	SubmissionZoneConfiguration *DomainSubmissionZoneConfiguration `json:"submission_zone_configuration,omitempty"`
	TeamSet *DomainTeamSet `json:"team_set,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	TimePenaltyConfiguration []DomainTimePenaltyConfiguration `json:"time_penalty_configuration,omitempty"`
	Timing *DomainTiming `json:"timing,omitempty"`
	Title *string `json:"title,omitempty"`
	WinnersPerGroup *int32 `json:"winners_per_group,omitempty"`
}

// NewDomainContest instantiates a new DomainContest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainContest() *DomainContest {
	this := DomainContest{}
	return &this
}

// NewDomainContestWithDefaults instantiates a new DomainContest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainContestWithDefaults() *DomainContest {
	this := DomainContest{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *DomainContest) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *DomainContest) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *DomainContest) SetCategory(v string) {
	o.Category = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *DomainContest) GetChannel() DomainChannel {
	if o == nil || IsNil(o.Channel) {
		var ret DomainChannel
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetChannelOk() (*DomainChannel, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *DomainContest) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given DomainChannel and assigns it to the Channel field.
func (o *DomainContest) SetChannel(v DomainChannel) {
	o.Channel = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DomainContest) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DomainContest) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DomainContest) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DomainContest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DomainContest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DomainContest) SetDescription(v string) {
	o.Description = &v
}

// GetDifficulty returns the Difficulty field value if set, zero value otherwise.
func (o *DomainContest) GetDifficulty() string {
	if o == nil || IsNil(o.Difficulty) {
		var ret string
		return ret
	}
	return *o.Difficulty
}

// GetDifficultyOk returns a tuple with the Difficulty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetDifficultyOk() (*string, bool) {
	if o == nil || IsNil(o.Difficulty) {
		return nil, false
	}
	return o.Difficulty, true
}

// HasDifficulty returns a boolean if a field has been set.
func (o *DomainContest) HasDifficulty() bool {
	if o != nil && !IsNil(o.Difficulty) {
		return true
	}

	return false
}

// SetDifficulty gets a reference to the given string and assigns it to the Difficulty field.
func (o *DomainContest) SetDifficulty(v string) {
	o.Difficulty = &v
}

// GetExtensionCount returns the ExtensionCount field value if set, zero value otherwise.
func (o *DomainContest) GetExtensionCount() int32 {
	if o == nil || IsNil(o.ExtensionCount) {
		var ret int32
		return ret
	}
	return *o.ExtensionCount
}

// GetExtensionCountOk returns a tuple with the ExtensionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetExtensionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ExtensionCount) {
		return nil, false
	}
	return o.ExtensionCount, true
}

// HasExtensionCount returns a boolean if a field has been set.
func (o *DomainContest) HasExtensionCount() bool {
	if o != nil && !IsNil(o.ExtensionCount) {
		return true
	}

	return false
}

// SetExtensionCount gets a reference to the given int32 and assigns it to the ExtensionCount field.
func (o *DomainContest) SetExtensionCount(v int32) {
	o.ExtensionCount = &v
}

// GetFairPlayGrouping returns the FairPlayGrouping field value if set, zero value otherwise.
func (o *DomainContest) GetFairPlayGrouping() bool {
	if o == nil || IsNil(o.FairPlayGrouping) {
		var ret bool
		return ret
	}
	return *o.FairPlayGrouping
}

// GetFairPlayGroupingOk returns a tuple with the FairPlayGrouping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetFairPlayGroupingOk() (*bool, bool) {
	if o == nil || IsNil(o.FairPlayGrouping) {
		return nil, false
	}
	return o.FairPlayGrouping, true
}

// HasFairPlayGrouping returns a boolean if a field has been set.
func (o *DomainContest) HasFairPlayGrouping() bool {
	if o != nil && !IsNil(o.FairPlayGrouping) {
		return true
	}

	return false
}

// SetFairPlayGrouping gets a reference to the given bool and assigns it to the FairPlayGrouping field.
func (o *DomainContest) SetFairPlayGrouping(v bool) {
	o.FairPlayGrouping = &v
}

// GetGroupingType returns the GroupingType field value if set, zero value otherwise.
func (o *DomainContest) GetGroupingType() string {
	if o == nil || IsNil(o.GroupingType) {
		var ret string
		return ret
	}
	return *o.GroupingType
}

// GetGroupingTypeOk returns a tuple with the GroupingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetGroupingTypeOk() (*string, bool) {
	if o == nil || IsNil(o.GroupingType) {
		return nil, false
	}
	return o.GroupingType, true
}

// HasGroupingType returns a boolean if a field has been set.
func (o *DomainContest) HasGroupingType() bool {
	if o != nil && !IsNil(o.GroupingType) {
		return true
	}

	return false
}

// SetGroupingType gets a reference to the given string and assigns it to the GroupingType field.
func (o *DomainContest) SetGroupingType(v string) {
	o.GroupingType = &v
}

// GetHeaderImageUrl returns the HeaderImageUrl field value if set, zero value otherwise.
func (o *DomainContest) GetHeaderImageUrl() string {
	if o == nil || IsNil(o.HeaderImageUrl) {
		var ret string
		return ret
	}
	return *o.HeaderImageUrl
}

// GetHeaderImageUrlOk returns a tuple with the HeaderImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetHeaderImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderImageUrl) {
		return nil, false
	}
	return o.HeaderImageUrl, true
}

// HasHeaderImageUrl returns a boolean if a field has been set.
func (o *DomainContest) HasHeaderImageUrl() bool {
	if o != nil && !IsNil(o.HeaderImageUrl) {
		return true
	}

	return false
}

// SetHeaderImageUrl gets a reference to the given string and assigns it to the HeaderImageUrl field.
func (o *DomainContest) SetHeaderImageUrl(v string) {
	o.HeaderImageUrl = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DomainContest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DomainContest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DomainContest) SetId(v string) {
	o.Id = &v
}

// GetJudgingDeadline returns the JudgingDeadline field value if set, zero value otherwise.
func (o *DomainContest) GetJudgingDeadline() string {
	if o == nil || IsNil(o.JudgingDeadline) {
		var ret string
		return ret
	}
	return *o.JudgingDeadline
}

// GetJudgingDeadlineOk returns a tuple with the JudgingDeadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetJudgingDeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.JudgingDeadline) {
		return nil, false
	}
	return o.JudgingDeadline, true
}

// HasJudgingDeadline returns a boolean if a field has been set.
func (o *DomainContest) HasJudgingDeadline() bool {
	if o != nil && !IsNil(o.JudgingDeadline) {
		return true
	}

	return false
}

// SetJudgingDeadline gets a reference to the given string and assigns it to the JudgingDeadline field.
func (o *DomainContest) SetJudgingDeadline(v string) {
	o.JudgingDeadline = &v
}

// GetJurorSelectionMode returns the JurorSelectionMode field value if set, zero value otherwise.
func (o *DomainContest) GetJurorSelectionMode() string {
	if o == nil || IsNil(o.JurorSelectionMode) {
		var ret string
		return ret
	}
	return *o.JurorSelectionMode
}

// GetJurorSelectionModeOk returns a tuple with the JurorSelectionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetJurorSelectionModeOk() (*string, bool) {
	if o == nil || IsNil(o.JurorSelectionMode) {
		return nil, false
	}
	return o.JurorSelectionMode, true
}

// HasJurorSelectionMode returns a boolean if a field has been set.
func (o *DomainContest) HasJurorSelectionMode() bool {
	if o != nil && !IsNil(o.JurorSelectionMode) {
		return true
	}

	return false
}

// SetJurorSelectionMode gets a reference to the given string and assigns it to the JurorSelectionMode field.
func (o *DomainContest) SetJurorSelectionMode(v string) {
	o.JurorSelectionMode = &v
}

// GetJurySize returns the JurySize field value if set, zero value otherwise.
func (o *DomainContest) GetJurySize() int32 {
	if o == nil || IsNil(o.JurySize) {
		var ret int32
		return ret
	}
	return *o.JurySize
}

// GetJurySizeOk returns a tuple with the JurySize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetJurySizeOk() (*int32, bool) {
	if o == nil || IsNil(o.JurySize) {
		return nil, false
	}
	return o.JurySize, true
}

// HasJurySize returns a boolean if a field has been set.
func (o *DomainContest) HasJurySize() bool {
	if o != nil && !IsNil(o.JurySize) {
		return true
	}

	return false
}

// SetJurySize gets a reference to the given int32 and assigns it to the JurySize field.
func (o *DomainContest) SetJurySize(v int32) {
	o.JurySize = &v
}

// GetMemberParticipation returns the MemberParticipation field value if set, zero value otherwise.
func (o *DomainContest) GetMemberParticipation() DomainMemberParticipationSummary {
	if o == nil || IsNil(o.MemberParticipation) {
		var ret DomainMemberParticipationSummary
		return ret
	}
	return *o.MemberParticipation
}

// GetMemberParticipationOk returns a tuple with the MemberParticipation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetMemberParticipationOk() (*DomainMemberParticipationSummary, bool) {
	if o == nil || IsNil(o.MemberParticipation) {
		return nil, false
	}
	return o.MemberParticipation, true
}

// HasMemberParticipation returns a boolean if a field has been set.
func (o *DomainContest) HasMemberParticipation() bool {
	if o != nil && !IsNil(o.MemberParticipation) {
		return true
	}

	return false
}

// SetMemberParticipation gets a reference to the given DomainMemberParticipationSummary and assigns it to the MemberParticipation field.
func (o *DomainContest) SetMemberParticipation(v DomainMemberParticipationSummary) {
	o.MemberParticipation = &v
}

// GetMinJurorScores returns the MinJurorScores field value if set, zero value otherwise.
func (o *DomainContest) GetMinJurorScores() int32 {
	if o == nil || IsNil(o.MinJurorScores) {
		var ret int32
		return ret
	}
	return *o.MinJurorScores
}

// GetMinJurorScoresOk returns a tuple with the MinJurorScores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetMinJurorScoresOk() (*int32, bool) {
	if o == nil || IsNil(o.MinJurorScores) {
		return nil, false
	}
	return o.MinJurorScores, true
}

// HasMinJurorScores returns a boolean if a field has been set.
func (o *DomainContest) HasMinJurorScores() bool {
	if o != nil && !IsNil(o.MinJurorScores) {
		return true
	}

	return false
}

// SetMinJurorScores gets a reference to the given int32 and assigns it to the MinJurorScores field.
func (o *DomainContest) SetMinJurorScores(v int32) {
	o.MinJurorScores = &v
}

// GetNoOfGroups returns the NoOfGroups field value if set, zero value otherwise.
func (o *DomainContest) GetNoOfGroups() int32 {
	if o == nil || IsNil(o.NoOfGroups) {
		var ret int32
		return ret
	}
	return *o.NoOfGroups
}

// GetNoOfGroupsOk returns a tuple with the NoOfGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetNoOfGroupsOk() (*int32, bool) {
	if o == nil || IsNil(o.NoOfGroups) {
		return nil, false
	}
	return o.NoOfGroups, true
}

// HasNoOfGroups returns a boolean if a field has been set.
func (o *DomainContest) HasNoOfGroups() bool {
	if o != nil && !IsNil(o.NoOfGroups) {
		return true
	}

	return false
}

// SetNoOfGroups gets a reference to the given int32 and assigns it to the NoOfGroups field.
func (o *DomainContest) SetNoOfGroups(v int32) {
	o.NoOfGroups = &v
}

// GetNoOfPuzzles returns the NoOfPuzzles field value if set, zero value otherwise.
func (o *DomainContest) GetNoOfPuzzles() int32 {
	if o == nil || IsNil(o.NoOfPuzzles) {
		var ret int32
		return ret
	}
	return *o.NoOfPuzzles
}

// GetNoOfPuzzlesOk returns a tuple with the NoOfPuzzles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetNoOfPuzzlesOk() (*int32, bool) {
	if o == nil || IsNil(o.NoOfPuzzles) {
		return nil, false
	}
	return o.NoOfPuzzles, true
}

// HasNoOfPuzzles returns a boolean if a field has been set.
func (o *DomainContest) HasNoOfPuzzles() bool {
	if o != nil && !IsNil(o.NoOfPuzzles) {
		return true
	}

	return false
}

// SetNoOfPuzzles gets a reference to the given int32 and assigns it to the NoOfPuzzles field.
func (o *DomainContest) SetNoOfPuzzles(v int32) {
	o.NoOfPuzzles = &v
}

// GetNoOfWinners returns the NoOfWinners field value if set, zero value otherwise.
func (o *DomainContest) GetNoOfWinners() int32 {
	if o == nil || IsNil(o.NoOfWinners) {
		var ret int32
		return ret
	}
	return *o.NoOfWinners
}

// GetNoOfWinnersOk returns a tuple with the NoOfWinners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetNoOfWinnersOk() (*int32, bool) {
	if o == nil || IsNil(o.NoOfWinners) {
		return nil, false
	}
	return o.NoOfWinners, true
}

// HasNoOfWinners returns a boolean if a field has been set.
func (o *DomainContest) HasNoOfWinners() bool {
	if o != nil && !IsNil(o.NoOfWinners) {
		return true
	}

	return false
}

// SetNoOfWinners gets a reference to the given int32 and assigns it to the NoOfWinners field.
func (o *DomainContest) SetNoOfWinners(v int32) {
	o.NoOfWinners = &v
}

// GetParticipationRules returns the ParticipationRules field value if set, zero value otherwise.
func (o *DomainContest) GetParticipationRules() DomainParticipationRules {
	if o == nil || IsNil(o.ParticipationRules) {
		var ret DomainParticipationRules
		return ret
	}
	return *o.ParticipationRules
}

// GetParticipationRulesOk returns a tuple with the ParticipationRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetParticipationRulesOk() (*DomainParticipationRules, bool) {
	if o == nil || IsNil(o.ParticipationRules) {
		return nil, false
	}
	return o.ParticipationRules, true
}

// HasParticipationRules returns a boolean if a field has been set.
func (o *DomainContest) HasParticipationRules() bool {
	if o != nil && !IsNil(o.ParticipationRules) {
		return true
	}

	return false
}

// SetParticipationRules gets a reference to the given DomainParticipationRules and assigns it to the ParticipationRules field.
func (o *DomainContest) SetParticipationRules(v DomainParticipationRules) {
	o.ParticipationRules = &v
}

// GetPuzzleSheetId returns the PuzzleSheetId field value if set, zero value otherwise.
func (o *DomainContest) GetPuzzleSheetId() string {
	if o == nil || IsNil(o.PuzzleSheetId) {
		var ret string
		return ret
	}
	return *o.PuzzleSheetId
}

// GetPuzzleSheetIdOk returns a tuple with the PuzzleSheetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetPuzzleSheetIdOk() (*string, bool) {
	if o == nil || IsNil(o.PuzzleSheetId) {
		return nil, false
	}
	return o.PuzzleSheetId, true
}

// HasPuzzleSheetId returns a boolean if a field has been set.
func (o *DomainContest) HasPuzzleSheetId() bool {
	if o != nil && !IsNil(o.PuzzleSheetId) {
		return true
	}

	return false
}

// SetPuzzleSheetId gets a reference to the given string and assigns it to the PuzzleSheetId field.
func (o *DomainContest) SetPuzzleSheetId(v string) {
	o.PuzzleSheetId = &v
}

// GetQuestionType returns the QuestionType field value if set, zero value otherwise.
func (o *DomainContest) GetQuestionType() DomainContestType {
	if o == nil || IsNil(o.QuestionType) {
		var ret DomainContestType
		return ret
	}
	return *o.QuestionType
}

// GetQuestionTypeOk returns a tuple with the QuestionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetQuestionTypeOk() (*DomainContestType, bool) {
	if o == nil || IsNil(o.QuestionType) {
		return nil, false
	}
	return o.QuestionType, true
}

// HasQuestionType returns a boolean if a field has been set.
func (o *DomainContest) HasQuestionType() bool {
	if o != nil && !IsNil(o.QuestionType) {
		return true
	}

	return false
}

// SetQuestionType gets a reference to the given DomainContestType and assigns it to the QuestionType field.
func (o *DomainContest) SetQuestionType(v DomainContestType) {
	o.QuestionType = &v
}

// GetReward returns the Reward field value if set, zero value otherwise.
func (o *DomainContest) GetReward() DomainReward {
	if o == nil || IsNil(o.Reward) {
		var ret DomainReward
		return ret
	}
	return *o.Reward
}

// GetRewardOk returns a tuple with the Reward field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetRewardOk() (*DomainReward, bool) {
	if o == nil || IsNil(o.Reward) {
		return nil, false
	}
	return o.Reward, true
}

// HasReward returns a boolean if a field has been set.
func (o *DomainContest) HasReward() bool {
	if o != nil && !IsNil(o.Reward) {
		return true
	}

	return false
}

// SetReward gets a reference to the given DomainReward and assigns it to the Reward field.
func (o *DomainContest) SetReward(v DomainReward) {
	o.Reward = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *DomainContest) GetSender() DomainPlatformIdentity {
	if o == nil || IsNil(o.Sender) {
		var ret DomainPlatformIdentity
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetSenderOk() (*DomainPlatformIdentity, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *DomainContest) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given DomainPlatformIdentity and assigns it to the Sender field.
func (o *DomainContest) SetSender(v DomainPlatformIdentity) {
	o.Sender = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *DomainContest) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *DomainContest) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *DomainContest) SetSourceId(v string) {
	o.SourceId = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *DomainContest) GetSourceType() DomainContestType {
	if o == nil || IsNil(o.SourceType) {
		var ret DomainContestType
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetSourceTypeOk() (*DomainContestType, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *DomainContest) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given DomainContestType and assigns it to the SourceType field.
func (o *DomainContest) SetSourceType(v DomainContestType) {
	o.SourceType = &v
}

// GetSponsor returns the Sponsor field value if set, zero value otherwise.
func (o *DomainContest) GetSponsor() DomainSponsorInfo {
	if o == nil || IsNil(o.Sponsor) {
		var ret DomainSponsorInfo
		return ret
	}
	return *o.Sponsor
}

// GetSponsorOk returns a tuple with the Sponsor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetSponsorOk() (*DomainSponsorInfo, bool) {
	if o == nil || IsNil(o.Sponsor) {
		return nil, false
	}
	return o.Sponsor, true
}

// HasSponsor returns a boolean if a field has been set.
func (o *DomainContest) HasSponsor() bool {
	if o != nil && !IsNil(o.Sponsor) {
		return true
	}

	return false
}

// SetSponsor gets a reference to the given DomainSponsorInfo and assigns it to the Sponsor field.
func (o *DomainContest) SetSponsor(v DomainSponsorInfo) {
	o.Sponsor = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DomainContest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DomainContest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *DomainContest) SetState(v string) {
	o.State = &v
}

// GetSubmissionZoneConfiguration returns the SubmissionZoneConfiguration field value if set, zero value otherwise.
func (o *DomainContest) GetSubmissionZoneConfiguration() DomainSubmissionZoneConfiguration {
	if o == nil || IsNil(o.SubmissionZoneConfiguration) {
		var ret DomainSubmissionZoneConfiguration
		return ret
	}
	return *o.SubmissionZoneConfiguration
}

// GetSubmissionZoneConfigurationOk returns a tuple with the SubmissionZoneConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetSubmissionZoneConfigurationOk() (*DomainSubmissionZoneConfiguration, bool) {
	if o == nil || IsNil(o.SubmissionZoneConfiguration) {
		return nil, false
	}
	return o.SubmissionZoneConfiguration, true
}

// HasSubmissionZoneConfiguration returns a boolean if a field has been set.
func (o *DomainContest) HasSubmissionZoneConfiguration() bool {
	if o != nil && !IsNil(o.SubmissionZoneConfiguration) {
		return true
	}

	return false
}

// SetSubmissionZoneConfiguration gets a reference to the given DomainSubmissionZoneConfiguration and assigns it to the SubmissionZoneConfiguration field.
func (o *DomainContest) SetSubmissionZoneConfiguration(v DomainSubmissionZoneConfiguration) {
	o.SubmissionZoneConfiguration = &v
}

// GetTeamSet returns the TeamSet field value if set, zero value otherwise.
func (o *DomainContest) GetTeamSet() DomainTeamSet {
	if o == nil || IsNil(o.TeamSet) {
		var ret DomainTeamSet
		return ret
	}
	return *o.TeamSet
}

// GetTeamSetOk returns a tuple with the TeamSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetTeamSetOk() (*DomainTeamSet, bool) {
	if o == nil || IsNil(o.TeamSet) {
		return nil, false
	}
	return o.TeamSet, true
}

// HasTeamSet returns a boolean if a field has been set.
func (o *DomainContest) HasTeamSet() bool {
	if o != nil && !IsNil(o.TeamSet) {
		return true
	}

	return false
}

// SetTeamSet gets a reference to the given DomainTeamSet and assigns it to the TeamSet field.
func (o *DomainContest) SetTeamSet(v DomainTeamSet) {
	o.TeamSet = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DomainContest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DomainContest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DomainContest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetTimePenaltyConfiguration returns the TimePenaltyConfiguration field value if set, zero value otherwise.
func (o *DomainContest) GetTimePenaltyConfiguration() []DomainTimePenaltyConfiguration {
	if o == nil || IsNil(o.TimePenaltyConfiguration) {
		var ret []DomainTimePenaltyConfiguration
		return ret
	}
	return o.TimePenaltyConfiguration
}

// GetTimePenaltyConfigurationOk returns a tuple with the TimePenaltyConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetTimePenaltyConfigurationOk() ([]DomainTimePenaltyConfiguration, bool) {
	if o == nil || IsNil(o.TimePenaltyConfiguration) {
		return nil, false
	}
	return o.TimePenaltyConfiguration, true
}

// HasTimePenaltyConfiguration returns a boolean if a field has been set.
func (o *DomainContest) HasTimePenaltyConfiguration() bool {
	if o != nil && !IsNil(o.TimePenaltyConfiguration) {
		return true
	}

	return false
}

// SetTimePenaltyConfiguration gets a reference to the given []DomainTimePenaltyConfiguration and assigns it to the TimePenaltyConfiguration field.
func (o *DomainContest) SetTimePenaltyConfiguration(v []DomainTimePenaltyConfiguration) {
	o.TimePenaltyConfiguration = v
}

// GetTiming returns the Timing field value if set, zero value otherwise.
func (o *DomainContest) GetTiming() DomainTiming {
	if o == nil || IsNil(o.Timing) {
		var ret DomainTiming
		return ret
	}
	return *o.Timing
}

// GetTimingOk returns a tuple with the Timing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetTimingOk() (*DomainTiming, bool) {
	if o == nil || IsNil(o.Timing) {
		return nil, false
	}
	return o.Timing, true
}

// HasTiming returns a boolean if a field has been set.
func (o *DomainContest) HasTiming() bool {
	if o != nil && !IsNil(o.Timing) {
		return true
	}

	return false
}

// SetTiming gets a reference to the given DomainTiming and assigns it to the Timing field.
func (o *DomainContest) SetTiming(v DomainTiming) {
	o.Timing = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *DomainContest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *DomainContest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *DomainContest) SetTitle(v string) {
	o.Title = &v
}

// GetWinnersPerGroup returns the WinnersPerGroup field value if set, zero value otherwise.
func (o *DomainContest) GetWinnersPerGroup() int32 {
	if o == nil || IsNil(o.WinnersPerGroup) {
		var ret int32
		return ret
	}
	return *o.WinnersPerGroup
}

// GetWinnersPerGroupOk returns a tuple with the WinnersPerGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainContest) GetWinnersPerGroupOk() (*int32, bool) {
	if o == nil || IsNil(o.WinnersPerGroup) {
		return nil, false
	}
	return o.WinnersPerGroup, true
}

// HasWinnersPerGroup returns a boolean if a field has been set.
func (o *DomainContest) HasWinnersPerGroup() bool {
	if o != nil && !IsNil(o.WinnersPerGroup) {
		return true
	}

	return false
}

// SetWinnersPerGroup gets a reference to the given int32 and assigns it to the WinnersPerGroup field.
func (o *DomainContest) SetWinnersPerGroup(v int32) {
	o.WinnersPerGroup = &v
}

func (o DomainContest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainContest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Difficulty) {
		toSerialize["difficulty"] = o.Difficulty
	}
	if !IsNil(o.ExtensionCount) {
		toSerialize["extension_count"] = o.ExtensionCount
	}
	if !IsNil(o.FairPlayGrouping) {
		toSerialize["fair_play_grouping"] = o.FairPlayGrouping
	}
	if !IsNil(o.GroupingType) {
		toSerialize["grouping_type"] = o.GroupingType
	}
	if !IsNil(o.HeaderImageUrl) {
		toSerialize["header_image_url"] = o.HeaderImageUrl
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JudgingDeadline) {
		toSerialize["judging_deadline"] = o.JudgingDeadline
	}
	if !IsNil(o.JurorSelectionMode) {
		toSerialize["juror_selection_mode"] = o.JurorSelectionMode
	}
	if !IsNil(o.JurySize) {
		toSerialize["jury_size"] = o.JurySize
	}
	if !IsNil(o.MemberParticipation) {
		toSerialize["member_participation"] = o.MemberParticipation
	}
	if !IsNil(o.MinJurorScores) {
		toSerialize["min_juror_scores"] = o.MinJurorScores
	}
	if !IsNil(o.NoOfGroups) {
		toSerialize["no_of_groups"] = o.NoOfGroups
	}
	if !IsNil(o.NoOfPuzzles) {
		toSerialize["no_of_puzzles"] = o.NoOfPuzzles
	}
	if !IsNil(o.NoOfWinners) {
		toSerialize["no_of_winners"] = o.NoOfWinners
	}
	if !IsNil(o.ParticipationRules) {
		toSerialize["participation_rules"] = o.ParticipationRules
	}
	if !IsNil(o.PuzzleSheetId) {
		toSerialize["puzzle_sheet_id"] = o.PuzzleSheetId
	}
	if !IsNil(o.QuestionType) {
		toSerialize["question_type"] = o.QuestionType
	}
	if !IsNil(o.Reward) {
		toSerialize["reward"] = o.Reward
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if !IsNil(o.SourceId) {
		toSerialize["source_id"] = o.SourceId
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.Sponsor) {
		toSerialize["sponsor"] = o.Sponsor
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.SubmissionZoneConfiguration) {
		toSerialize["submission_zone_configuration"] = o.SubmissionZoneConfiguration
	}
	if !IsNil(o.TeamSet) {
		toSerialize["team_set"] = o.TeamSet
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.TimePenaltyConfiguration) {
		toSerialize["time_penalty_configuration"] = o.TimePenaltyConfiguration
	}
	if !IsNil(o.Timing) {
		toSerialize["timing"] = o.Timing
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.WinnersPerGroup) {
		toSerialize["winners_per_group"] = o.WinnersPerGroup
	}
	return toSerialize, nil
}

type NullableDomainContest struct {
	value *DomainContest
	isSet bool
}

func (v NullableDomainContest) Get() *DomainContest {
	return v.value
}

func (v *NullableDomainContest) Set(val *DomainContest) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainContest) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainContest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainContest(val *DomainContest) *NullableDomainContest {
	return &NullableDomainContest{value: val, isSet: true}
}

func (v NullableDomainContest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainContest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


