/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestUpdateChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestUpdateChannelRequest{}

// RequestUpdateChannelRequest struct for RequestUpdateChannelRequest
type RequestUpdateChannelRequest struct {
	AccessType *string `json:"access_type,omitempty"`
	HeaderImageUrl string `json:"header_image_url"`
	IsFanChannel *bool `json:"is_fan_channel,omitempty"`
	Name string `json:"name"`
	Regions []RequestRegion `json:"regions,omitempty"`
	Size int32 `json:"size"`
}

type _RequestUpdateChannelRequest RequestUpdateChannelRequest

// NewRequestUpdateChannelRequest instantiates a new RequestUpdateChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestUpdateChannelRequest(headerImageUrl string, name string, size int32) *RequestUpdateChannelRequest {
	this := RequestUpdateChannelRequest{}
	this.HeaderImageUrl = headerImageUrl
	this.Name = name
	this.Size = size
	return &this
}

// NewRequestUpdateChannelRequestWithDefaults instantiates a new RequestUpdateChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestUpdateChannelRequestWithDefaults() *RequestUpdateChannelRequest {
	this := RequestUpdateChannelRequest{}
	return &this
}

// GetAccessType returns the AccessType field value if set, zero value otherwise.
func (o *RequestUpdateChannelRequest) GetAccessType() string {
	if o == nil || IsNil(o.AccessType) {
		var ret string
		return ret
	}
	return *o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetAccessTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccessType) {
		return nil, false
	}
	return o.AccessType, true
}

// HasAccessType returns a boolean if a field has been set.
func (o *RequestUpdateChannelRequest) HasAccessType() bool {
	if o != nil && !IsNil(o.AccessType) {
		return true
	}

	return false
}

// SetAccessType gets a reference to the given string and assigns it to the AccessType field.
func (o *RequestUpdateChannelRequest) SetAccessType(v string) {
	o.AccessType = &v
}

// GetHeaderImageUrl returns the HeaderImageUrl field value
func (o *RequestUpdateChannelRequest) GetHeaderImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HeaderImageUrl
}

// GetHeaderImageUrlOk returns a tuple with the HeaderImageUrl field value
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetHeaderImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeaderImageUrl, true
}

// SetHeaderImageUrl sets field value
func (o *RequestUpdateChannelRequest) SetHeaderImageUrl(v string) {
	o.HeaderImageUrl = v
}

// GetIsFanChannel returns the IsFanChannel field value if set, zero value otherwise.
func (o *RequestUpdateChannelRequest) GetIsFanChannel() bool {
	if o == nil || IsNil(o.IsFanChannel) {
		var ret bool
		return ret
	}
	return *o.IsFanChannel
}

// GetIsFanChannelOk returns a tuple with the IsFanChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetIsFanChannelOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFanChannel) {
		return nil, false
	}
	return o.IsFanChannel, true
}

// HasIsFanChannel returns a boolean if a field has been set.
func (o *RequestUpdateChannelRequest) HasIsFanChannel() bool {
	if o != nil && !IsNil(o.IsFanChannel) {
		return true
	}

	return false
}

// SetIsFanChannel gets a reference to the given bool and assigns it to the IsFanChannel field.
func (o *RequestUpdateChannelRequest) SetIsFanChannel(v bool) {
	o.IsFanChannel = &v
}

// GetName returns the Name field value
func (o *RequestUpdateChannelRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RequestUpdateChannelRequest) SetName(v string) {
	o.Name = v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *RequestUpdateChannelRequest) GetRegions() []RequestRegion {
	if o == nil || IsNil(o.Regions) {
		var ret []RequestRegion
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetRegionsOk() ([]RequestRegion, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *RequestUpdateChannelRequest) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []RequestRegion and assigns it to the Regions field.
func (o *RequestUpdateChannelRequest) SetRegions(v []RequestRegion) {
	o.Regions = v
}

// GetSize returns the Size field value
func (o *RequestUpdateChannelRequest) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *RequestUpdateChannelRequest) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *RequestUpdateChannelRequest) SetSize(v int32) {
	o.Size = v
}

func (o RequestUpdateChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestUpdateChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessType) {
		toSerialize["access_type"] = o.AccessType
	}
	toSerialize["header_image_url"] = o.HeaderImageUrl
	if !IsNil(o.IsFanChannel) {
		toSerialize["is_fan_channel"] = o.IsFanChannel
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *RequestUpdateChannelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"header_image_url",
		"name",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestUpdateChannelRequest := _RequestUpdateChannelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestUpdateChannelRequest)

	if err != nil {
		return err
	}

	*o = RequestUpdateChannelRequest(varRequestUpdateChannelRequest)

	return err
}

type NullableRequestUpdateChannelRequest struct {
	value *RequestUpdateChannelRequest
	isSet bool
}

func (v NullableRequestUpdateChannelRequest) Get() *RequestUpdateChannelRequest {
	return v.value
}

func (v *NullableRequestUpdateChannelRequest) Set(val *RequestUpdateChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestUpdateChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestUpdateChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestUpdateChannelRequest(val *RequestUpdateChannelRequest) *NullableRequestUpdateChannelRequest {
	return &NullableRequestUpdateChannelRequest{value: val, isSet: true}
}

func (v NullableRequestUpdateChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestUpdateChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


