/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestSelectGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestSelectGroupRequest{}

// RequestSelectGroupRequest struct for RequestSelectGroupRequest
type RequestSelectGroupRequest struct {
	Group string `json:"group"`
}

type _RequestSelectGroupRequest RequestSelectGroupRequest

// NewRequestSelectGroupRequest instantiates a new RequestSelectGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestSelectGroupRequest(group string) *RequestSelectGroupRequest {
	this := RequestSelectGroupRequest{}
	this.Group = group
	return &this
}

// NewRequestSelectGroupRequestWithDefaults instantiates a new RequestSelectGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestSelectGroupRequestWithDefaults() *RequestSelectGroupRequest {
	this := RequestSelectGroupRequest{}
	return &this
}

// GetGroup returns the Group field value
func (o *RequestSelectGroupRequest) GetGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *RequestSelectGroupRequest) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *RequestSelectGroupRequest) SetGroup(v string) {
	o.Group = v
}

func (o RequestSelectGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestSelectGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	return toSerialize, nil
}

func (o *RequestSelectGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestSelectGroupRequest := _RequestSelectGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestSelectGroupRequest)

	if err != nil {
		return err
	}

	*o = RequestSelectGroupRequest(varRequestSelectGroupRequest)

	return err
}

type NullableRequestSelectGroupRequest struct {
	value *RequestSelectGroupRequest
	isSet bool
}

func (v NullableRequestSelectGroupRequest) Get() *RequestSelectGroupRequest {
	return v.value
}

func (v *NullableRequestSelectGroupRequest) Set(val *RequestSelectGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestSelectGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestSelectGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestSelectGroupRequest(val *RequestSelectGroupRequest) *NullableRequestSelectGroupRequest {
	return &NullableRequestSelectGroupRequest{value: val, isSet: true}
}

func (v NullableRequestSelectGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestSelectGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


