/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPublicContestsByIdGroupedScoreboard200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicContestsByIdGroupedScoreboard200Response{}

// GetPublicContestsByIdGroupedScoreboard200Response struct for GetPublicContestsByIdGroupedScoreboard200Response
type GetPublicContestsByIdGroupedScoreboard200Response struct {
	Data DomainGroupedScoreBoard `json:"data"`
}

type _GetPublicContestsByIdGroupedScoreboard200Response GetPublicContestsByIdGroupedScoreboard200Response

// NewGetPublicContestsByIdGroupedScoreboard200Response instantiates a new GetPublicContestsByIdGroupedScoreboard200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicContestsByIdGroupedScoreboard200Response(data DomainGroupedScoreBoard) *GetPublicContestsByIdGroupedScoreboard200Response {
	this := GetPublicContestsByIdGroupedScoreboard200Response{}
	this.Data = data
	return &this
}

// NewGetPublicContestsByIdGroupedScoreboard200ResponseWithDefaults instantiates a new GetPublicContestsByIdGroupedScoreboard200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicContestsByIdGroupedScoreboard200ResponseWithDefaults() *GetPublicContestsByIdGroupedScoreboard200Response {
	this := GetPublicContestsByIdGroupedScoreboard200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetPublicContestsByIdGroupedScoreboard200Response) GetData() DomainGroupedScoreBoard {
	if o == nil {
		var ret DomainGroupedScoreBoard
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetPublicContestsByIdGroupedScoreboard200Response) GetDataOk() (*DomainGroupedScoreBoard, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetPublicContestsByIdGroupedScoreboard200Response) SetData(v DomainGroupedScoreBoard) {
	o.Data = v
}

func (o GetPublicContestsByIdGroupedScoreboard200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPublicContestsByIdGroupedScoreboard200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetPublicContestsByIdGroupedScoreboard200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPublicContestsByIdGroupedScoreboard200Response := _GetPublicContestsByIdGroupedScoreboard200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPublicContestsByIdGroupedScoreboard200Response)

	if err != nil {
		return err
	}

	*o = GetPublicContestsByIdGroupedScoreboard200Response(varGetPublicContestsByIdGroupedScoreboard200Response)

	return err
}

type NullableGetPublicContestsByIdGroupedScoreboard200Response struct {
	value *GetPublicContestsByIdGroupedScoreboard200Response
	isSet bool
}

func (v NullableGetPublicContestsByIdGroupedScoreboard200Response) Get() *GetPublicContestsByIdGroupedScoreboard200Response {
	return v.value
}

func (v *NullableGetPublicContestsByIdGroupedScoreboard200Response) Set(val *GetPublicContestsByIdGroupedScoreboard200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicContestsByIdGroupedScoreboard200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicContestsByIdGroupedScoreboard200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicContestsByIdGroupedScoreboard200Response(val *GetPublicContestsByIdGroupedScoreboard200Response) *NullableGetPublicContestsByIdGroupedScoreboard200Response {
	return &NullableGetPublicContestsByIdGroupedScoreboard200Response{value: val, isSet: true}
}

func (v NullableGetPublicContestsByIdGroupedScoreboard200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicContestsByIdGroupedScoreboard200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


