/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainVenue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainVenue{}

// DomainVenue struct for DomainVenue
type DomainVenue struct {
	ExternalRef *string `json:"external_ref,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	TenantId *string `json:"tenant_id,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewDomainVenue instantiates a new DomainVenue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainVenue() *DomainVenue {
	this := DomainVenue{}
	return &this
}

// NewDomainVenueWithDefaults instantiates a new DomainVenue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainVenueWithDefaults() *DomainVenue {
	this := DomainVenue{}
	return &this
}

// GetExternalRef returns the ExternalRef field value if set, zero value otherwise.
func (o *DomainVenue) GetExternalRef() string {
	if o == nil || IsNil(o.ExternalRef) {
		var ret string
		return ret
	}
	return *o.ExternalRef
}

// GetExternalRefOk returns a tuple with the ExternalRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainVenue) GetExternalRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalRef) {
		return nil, false
	}
	return o.ExternalRef, true
}

// HasExternalRef returns a boolean if a field has been set.
func (o *DomainVenue) HasExternalRef() bool {
	if o != nil && !IsNil(o.ExternalRef) {
		return true
	}

	return false
}

// SetExternalRef gets a reference to the given string and assigns it to the ExternalRef field.
func (o *DomainVenue) SetExternalRef(v string) {
	o.ExternalRef = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DomainVenue) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainVenue) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DomainVenue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DomainVenue) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DomainVenue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainVenue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DomainVenue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DomainVenue) SetName(v string) {
	o.Name = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *DomainVenue) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainVenue) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *DomainVenue) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *DomainVenue) SetTenantId(v string) {
	o.TenantId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DomainVenue) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainVenue) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DomainVenue) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DomainVenue) SetType(v string) {
	o.Type = &v
}

func (o DomainVenue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainVenue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalRef) {
		toSerialize["external_ref"] = o.ExternalRef
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableDomainVenue struct {
	value *DomainVenue
	isSet bool
}

func (v NullableDomainVenue) Get() *DomainVenue {
	return v.value
}

func (v *NullableDomainVenue) Set(val *DomainVenue) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainVenue) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainVenue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainVenue(val *DomainVenue) *NullableDomainVenue {
	return &NullableDomainVenue{value: val, isSet: true}
}

func (v NullableDomainVenue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainVenue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


