/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetChannelsByIdTournaments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChannelsByIdTournaments200Response{}

// GetChannelsByIdTournaments200Response struct for GetChannelsByIdTournaments200Response
type GetChannelsByIdTournaments200Response struct {
	Data []DomainTournament `json:"data"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

type _GetChannelsByIdTournaments200Response GetChannelsByIdTournaments200Response

// NewGetChannelsByIdTournaments200Response instantiates a new GetChannelsByIdTournaments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChannelsByIdTournaments200Response(data []DomainTournament) *GetChannelsByIdTournaments200Response {
	this := GetChannelsByIdTournaments200Response{}
	this.Data = data
	return &this
}

// NewGetChannelsByIdTournaments200ResponseWithDefaults instantiates a new GetChannelsByIdTournaments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChannelsByIdTournaments200ResponseWithDefaults() *GetChannelsByIdTournaments200Response {
	this := GetChannelsByIdTournaments200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetChannelsByIdTournaments200Response) GetData() []DomainTournament {
	if o == nil {
		var ret []DomainTournament
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetChannelsByIdTournaments200Response) GetDataOk() ([]DomainTournament, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetChannelsByIdTournaments200Response) SetData(v []DomainTournament) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GetChannelsByIdTournaments200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChannelsByIdTournaments200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GetChannelsByIdTournaments200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *GetChannelsByIdTournaments200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o GetChannelsByIdTournaments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChannelsByIdTournaments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

func (o *GetChannelsByIdTournaments200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetChannelsByIdTournaments200Response := _GetChannelsByIdTournaments200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetChannelsByIdTournaments200Response)

	if err != nil {
		return err
	}

	*o = GetChannelsByIdTournaments200Response(varGetChannelsByIdTournaments200Response)

	return err
}

type NullableGetChannelsByIdTournaments200Response struct {
	value *GetChannelsByIdTournaments200Response
	isSet bool
}

func (v NullableGetChannelsByIdTournaments200Response) Get() *GetChannelsByIdTournaments200Response {
	return v.value
}

func (v *NullableGetChannelsByIdTournaments200Response) Set(val *GetChannelsByIdTournaments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChannelsByIdTournaments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChannelsByIdTournaments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChannelsByIdTournaments200Response(val *GetChannelsByIdTournaments200Response) *NullableGetChannelsByIdTournaments200Response {
	return &NullableGetChannelsByIdTournaments200Response{value: val, isSet: true}
}

func (v NullableGetChannelsByIdTournaments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChannelsByIdTournaments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


