/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Event type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Event{}

// Event A prediction event — sports match, election, user-created event, etc.
type Event struct {
	Category NullableString `json:"category,omitempty"`
	Description NullableString `json:"description,omitempty"`
	EndTime NullableTime `json:"end_time,omitempty"`
	EsEventId NullableString `json:"es_event_id,omitempty"`
	Family NullableString `json:"family,omitempty"`
	Id string `json:"id"`
	InsertedAt *time.Time `json:"inserted_at,omitempty"`
	Items []EventItem `json:"items,omitempty"`
	Name string `json:"name"`
	OwnerId NullableString `json:"owner_id,omitempty"`
	Provider string `json:"provider"`
	ProviderId NullableString `json:"provider_id,omitempty"`
	// Result payload — shape depends on event item types.
	Result map[string]interface{} `json:"result,omitempty"`
	ResultApproved NullableBool `json:"result_approved,omitempty"`
	ResultApprovedAt NullableTime `json:"result_approved_at,omitempty"`
	ResultApprovedBy NullableString `json:"result_approved_by,omitempty"`
	ResultEnteredAt NullableTime `json:"result_entered_at,omitempty"`
	StartTime NullableTime `json:"start_time,omitempty"`
	Status *string `json:"status,omitempty"`
	TemplateId NullableString `json:"template_id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Visibility NullableString `json:"visibility,omitempty"`
}

type _Event Event

// NewEvent instantiates a new Event object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEvent(id string, name string, provider string) *Event {
	this := Event{}
	this.Id = id
	this.Name = name
	this.Provider = provider
	return &this
}

// NewEventWithDefaults instantiates a new Event object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventWithDefaults() *Event {
	this := Event{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *Event) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *Event) SetCategory(v string) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *Event) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *Event) UnsetCategory() {
	o.Category.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Event) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Event) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Event) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Event) UnsetDescription() {
	o.Description.Unset()
}

// GetEndTime returns the EndTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// HasEndTime returns a boolean if a field has been set.
func (o *Event) HasEndTime() bool {
	if o != nil && o.EndTime.IsSet() {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given NullableTime and assigns it to the EndTime field.
func (o *Event) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}
// SetEndTimeNil sets the value for EndTime to be an explicit nil
func (o *Event) SetEndTimeNil() {
	o.EndTime.Set(nil)
}

// UnsetEndTime ensures that no value is present for EndTime, not even an explicit nil
func (o *Event) UnsetEndTime() {
	o.EndTime.Unset()
}

// GetEsEventId returns the EsEventId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetEsEventId() string {
	if o == nil || IsNil(o.EsEventId.Get()) {
		var ret string
		return ret
	}
	return *o.EsEventId.Get()
}

// GetEsEventIdOk returns a tuple with the EsEventId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetEsEventIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EsEventId.Get(), o.EsEventId.IsSet()
}

// HasEsEventId returns a boolean if a field has been set.
func (o *Event) HasEsEventId() bool {
	if o != nil && o.EsEventId.IsSet() {
		return true
	}

	return false
}

// SetEsEventId gets a reference to the given NullableString and assigns it to the EsEventId field.
func (o *Event) SetEsEventId(v string) {
	o.EsEventId.Set(&v)
}
// SetEsEventIdNil sets the value for EsEventId to be an explicit nil
func (o *Event) SetEsEventIdNil() {
	o.EsEventId.Set(nil)
}

// UnsetEsEventId ensures that no value is present for EsEventId, not even an explicit nil
func (o *Event) UnsetEsEventId() {
	o.EsEventId.Unset()
}

// GetFamily returns the Family field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetFamily() string {
	if o == nil || IsNil(o.Family.Get()) {
		var ret string
		return ret
	}
	return *o.Family.Get()
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetFamilyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Family.Get(), o.Family.IsSet()
}

// HasFamily returns a boolean if a field has been set.
func (o *Event) HasFamily() bool {
	if o != nil && o.Family.IsSet() {
		return true
	}

	return false
}

// SetFamily gets a reference to the given NullableString and assigns it to the Family field.
func (o *Event) SetFamily(v string) {
	o.Family.Set(&v)
}
// SetFamilyNil sets the value for Family to be an explicit nil
func (o *Event) SetFamilyNil() {
	o.Family.Set(nil)
}

// UnsetFamily ensures that no value is present for Family, not even an explicit nil
func (o *Event) UnsetFamily() {
	o.Family.Unset()
}

// GetId returns the Id field value
func (o *Event) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Event) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Event) SetId(v string) {
	o.Id = v
}

// GetInsertedAt returns the InsertedAt field value if set, zero value otherwise.
func (o *Event) GetInsertedAt() time.Time {
	if o == nil || IsNil(o.InsertedAt) {
		var ret time.Time
		return ret
	}
	return *o.InsertedAt
}

// GetInsertedAtOk returns a tuple with the InsertedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetInsertedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InsertedAt) {
		return nil, false
	}
	return o.InsertedAt, true
}

// HasInsertedAt returns a boolean if a field has been set.
func (o *Event) HasInsertedAt() bool {
	if o != nil && !IsNil(o.InsertedAt) {
		return true
	}

	return false
}

// SetInsertedAt gets a reference to the given time.Time and assigns it to the InsertedAt field.
func (o *Event) SetInsertedAt(v time.Time) {
	o.InsertedAt = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *Event) GetItems() []EventItem {
	if o == nil || IsNil(o.Items) {
		var ret []EventItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetItemsOk() ([]EventItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *Event) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []EventItem and assigns it to the Items field.
func (o *Event) SetItems(v []EventItem) {
	o.Items = v
}

// GetName returns the Name field value
func (o *Event) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Event) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Event) SetName(v string) {
	o.Name = v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetOwnerId() string {
	if o == nil || IsNil(o.OwnerId.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerId.Get()
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerId.Get(), o.OwnerId.IsSet()
}

// HasOwnerId returns a boolean if a field has been set.
func (o *Event) HasOwnerId() bool {
	if o != nil && o.OwnerId.IsSet() {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given NullableString and assigns it to the OwnerId field.
func (o *Event) SetOwnerId(v string) {
	o.OwnerId.Set(&v)
}
// SetOwnerIdNil sets the value for OwnerId to be an explicit nil
func (o *Event) SetOwnerIdNil() {
	o.OwnerId.Set(nil)
}

// UnsetOwnerId ensures that no value is present for OwnerId, not even an explicit nil
func (o *Event) UnsetOwnerId() {
	o.OwnerId.Unset()
}

// GetProvider returns the Provider field value
func (o *Event) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *Event) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *Event) SetProvider(v string) {
	o.Provider = v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId.Get()) {
		var ret string
		return ret
	}
	return *o.ProviderId.Get()
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderId.Get(), o.ProviderId.IsSet()
}

// HasProviderId returns a boolean if a field has been set.
func (o *Event) HasProviderId() bool {
	if o != nil && o.ProviderId.IsSet() {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given NullableString and assigns it to the ProviderId field.
func (o *Event) SetProviderId(v string) {
	o.ProviderId.Set(&v)
}
// SetProviderIdNil sets the value for ProviderId to be an explicit nil
func (o *Event) SetProviderIdNil() {
	o.ProviderId.Set(nil)
}

// UnsetProviderId ensures that no value is present for ProviderId, not even an explicit nil
func (o *Event) UnsetProviderId() {
	o.ProviderId.Unset()
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetResult() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *Event) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *Event) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetResultApproved returns the ResultApproved field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetResultApproved() bool {
	if o == nil || IsNil(o.ResultApproved.Get()) {
		var ret bool
		return ret
	}
	return *o.ResultApproved.Get()
}

// GetResultApprovedOk returns a tuple with the ResultApproved field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetResultApprovedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultApproved.Get(), o.ResultApproved.IsSet()
}

// HasResultApproved returns a boolean if a field has been set.
func (o *Event) HasResultApproved() bool {
	if o != nil && o.ResultApproved.IsSet() {
		return true
	}

	return false
}

// SetResultApproved gets a reference to the given NullableBool and assigns it to the ResultApproved field.
func (o *Event) SetResultApproved(v bool) {
	o.ResultApproved.Set(&v)
}
// SetResultApprovedNil sets the value for ResultApproved to be an explicit nil
func (o *Event) SetResultApprovedNil() {
	o.ResultApproved.Set(nil)
}

// UnsetResultApproved ensures that no value is present for ResultApproved, not even an explicit nil
func (o *Event) UnsetResultApproved() {
	o.ResultApproved.Unset()
}

// GetResultApprovedAt returns the ResultApprovedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetResultApprovedAt() time.Time {
	if o == nil || IsNil(o.ResultApprovedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ResultApprovedAt.Get()
}

// GetResultApprovedAtOk returns a tuple with the ResultApprovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetResultApprovedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultApprovedAt.Get(), o.ResultApprovedAt.IsSet()
}

// HasResultApprovedAt returns a boolean if a field has been set.
func (o *Event) HasResultApprovedAt() bool {
	if o != nil && o.ResultApprovedAt.IsSet() {
		return true
	}

	return false
}

// SetResultApprovedAt gets a reference to the given NullableTime and assigns it to the ResultApprovedAt field.
func (o *Event) SetResultApprovedAt(v time.Time) {
	o.ResultApprovedAt.Set(&v)
}
// SetResultApprovedAtNil sets the value for ResultApprovedAt to be an explicit nil
func (o *Event) SetResultApprovedAtNil() {
	o.ResultApprovedAt.Set(nil)
}

// UnsetResultApprovedAt ensures that no value is present for ResultApprovedAt, not even an explicit nil
func (o *Event) UnsetResultApprovedAt() {
	o.ResultApprovedAt.Unset()
}

// GetResultApprovedBy returns the ResultApprovedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetResultApprovedBy() string {
	if o == nil || IsNil(o.ResultApprovedBy.Get()) {
		var ret string
		return ret
	}
	return *o.ResultApprovedBy.Get()
}

// GetResultApprovedByOk returns a tuple with the ResultApprovedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetResultApprovedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultApprovedBy.Get(), o.ResultApprovedBy.IsSet()
}

// HasResultApprovedBy returns a boolean if a field has been set.
func (o *Event) HasResultApprovedBy() bool {
	if o != nil && o.ResultApprovedBy.IsSet() {
		return true
	}

	return false
}

// SetResultApprovedBy gets a reference to the given NullableString and assigns it to the ResultApprovedBy field.
func (o *Event) SetResultApprovedBy(v string) {
	o.ResultApprovedBy.Set(&v)
}
// SetResultApprovedByNil sets the value for ResultApprovedBy to be an explicit nil
func (o *Event) SetResultApprovedByNil() {
	o.ResultApprovedBy.Set(nil)
}

// UnsetResultApprovedBy ensures that no value is present for ResultApprovedBy, not even an explicit nil
func (o *Event) UnsetResultApprovedBy() {
	o.ResultApprovedBy.Unset()
}

// GetResultEnteredAt returns the ResultEnteredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetResultEnteredAt() time.Time {
	if o == nil || IsNil(o.ResultEnteredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ResultEnteredAt.Get()
}

// GetResultEnteredAtOk returns a tuple with the ResultEnteredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetResultEnteredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultEnteredAt.Get(), o.ResultEnteredAt.IsSet()
}

// HasResultEnteredAt returns a boolean if a field has been set.
func (o *Event) HasResultEnteredAt() bool {
	if o != nil && o.ResultEnteredAt.IsSet() {
		return true
	}

	return false
}

// SetResultEnteredAt gets a reference to the given NullableTime and assigns it to the ResultEnteredAt field.
func (o *Event) SetResultEnteredAt(v time.Time) {
	o.ResultEnteredAt.Set(&v)
}
// SetResultEnteredAtNil sets the value for ResultEnteredAt to be an explicit nil
func (o *Event) SetResultEnteredAtNil() {
	o.ResultEnteredAt.Set(nil)
}

// UnsetResultEnteredAt ensures that no value is present for ResultEnteredAt, not even an explicit nil
func (o *Event) UnsetResultEnteredAt() {
	o.ResultEnteredAt.Unset()
}

// GetStartTime returns the StartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartTime.Get()
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartTime.Get(), o.StartTime.IsSet()
}

// HasStartTime returns a boolean if a field has been set.
func (o *Event) HasStartTime() bool {
	if o != nil && o.StartTime.IsSet() {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given NullableTime and assigns it to the StartTime field.
func (o *Event) SetStartTime(v time.Time) {
	o.StartTime.Set(&v)
}
// SetStartTimeNil sets the value for StartTime to be an explicit nil
func (o *Event) SetStartTimeNil() {
	o.StartTime.Set(nil)
}

// UnsetStartTime ensures that no value is present for StartTime, not even an explicit nil
func (o *Event) UnsetStartTime() {
	o.StartTime.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Event) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Event) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Event) SetStatus(v string) {
	o.Status = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId.Get()) {
		var ret string
		return ret
	}
	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// HasTemplateId returns a boolean if a field has been set.
func (o *Event) HasTemplateId() bool {
	if o != nil && o.TemplateId.IsSet() {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given NullableString and assigns it to the TemplateId field.
func (o *Event) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}
// SetTemplateIdNil sets the value for TemplateId to be an explicit nil
func (o *Event) SetTemplateIdNil() {
	o.TemplateId.Set(nil)
}

// UnsetTemplateId ensures that no value is present for TemplateId, not even an explicit nil
func (o *Event) UnsetTemplateId() {
	o.TemplateId.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Event) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Event) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Event) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Event) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Event) GetVisibility() string {
	if o == nil || IsNil(o.Visibility.Get()) {
		var ret string
		return ret
	}
	return *o.Visibility.Get()
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Event) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Visibility.Get(), o.Visibility.IsSet()
}

// HasVisibility returns a boolean if a field has been set.
func (o *Event) HasVisibility() bool {
	if o != nil && o.Visibility.IsSet() {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given NullableString and assigns it to the Visibility field.
func (o *Event) SetVisibility(v string) {
	o.Visibility.Set(&v)
}
// SetVisibilityNil sets the value for Visibility to be an explicit nil
func (o *Event) SetVisibilityNil() {
	o.Visibility.Set(nil)
}

// UnsetVisibility ensures that no value is present for Visibility, not even an explicit nil
func (o *Event) UnsetVisibility() {
	o.Visibility.Unset()
}

func (o Event) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Event) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.EndTime.IsSet() {
		toSerialize["end_time"] = o.EndTime.Get()
	}
	if o.EsEventId.IsSet() {
		toSerialize["es_event_id"] = o.EsEventId.Get()
	}
	if o.Family.IsSet() {
		toSerialize["family"] = o.Family.Get()
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.InsertedAt) {
		toSerialize["inserted_at"] = o.InsertedAt
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	toSerialize["name"] = o.Name
	if o.OwnerId.IsSet() {
		toSerialize["owner_id"] = o.OwnerId.Get()
	}
	toSerialize["provider"] = o.Provider
	if o.ProviderId.IsSet() {
		toSerialize["provider_id"] = o.ProviderId.Get()
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.ResultApproved.IsSet() {
		toSerialize["result_approved"] = o.ResultApproved.Get()
	}
	if o.ResultApprovedAt.IsSet() {
		toSerialize["result_approved_at"] = o.ResultApprovedAt.Get()
	}
	if o.ResultApprovedBy.IsSet() {
		toSerialize["result_approved_by"] = o.ResultApprovedBy.Get()
	}
	if o.ResultEnteredAt.IsSet() {
		toSerialize["result_entered_at"] = o.ResultEnteredAt.Get()
	}
	if o.StartTime.IsSet() {
		toSerialize["start_time"] = o.StartTime.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.TemplateId.IsSet() {
		toSerialize["template_id"] = o.TemplateId.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.Visibility.IsSet() {
		toSerialize["visibility"] = o.Visibility.Get()
	}
	return toSerialize, nil
}

func (o *Event) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEvent := _Event{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEvent)

	if err != nil {
		return err
	}

	*o = Event(varEvent)

	return err
}

type NullableEvent struct {
	value *Event
	isSet bool
}

func (v NullableEvent) Get() *Event {
	return v.value
}

func (v *NullableEvent) Set(val *Event) {
	v.value = val
	v.isSet = true
}

func (v NullableEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEvent(val *Event) *NullableEvent {
	return &NullableEvent{value: val, isSet: true}
}

func (v NullableEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


