/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PuzzleSheet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PuzzleSheet{}

// PuzzleSheet A curated or adhoc set of puzzles.
type PuzzleSheet struct {
	Description NullableString `json:"description,omitempty"`
	Id string `json:"id"`
	InsertedAt *time.Time `json:"inserted_at,omitempty"`
	IsAdhocSheet NullableBool `json:"is_adhoc_sheet,omitempty"`
	IsCommunityQuestions NullableBool `json:"is_community_questions,omitempty"`
	Name string `json:"name"`
	OwnerId string `json:"owner_id"`
	// Embedded puzzle bodies. Empty for adhoc sheet stubs.
	Puzzles []PuzzleBody `json:"puzzles,omitempty"`
	Tags []string `json:"tags,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Visibility string `json:"visibility"`
}

type _PuzzleSheet PuzzleSheet

// NewPuzzleSheet instantiates a new PuzzleSheet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPuzzleSheet(id string, name string, ownerId string, visibility string) *PuzzleSheet {
	this := PuzzleSheet{}
	this.Id = id
	this.Name = name
	this.OwnerId = ownerId
	this.Visibility = visibility
	return &this
}

// NewPuzzleSheetWithDefaults instantiates a new PuzzleSheet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPuzzleSheetWithDefaults() *PuzzleSheet {
	this := PuzzleSheet{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleSheet) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleSheet) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *PuzzleSheet) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *PuzzleSheet) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *PuzzleSheet) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *PuzzleSheet) UnsetDescription() {
	o.Description.Unset()
}

// GetId returns the Id field value
func (o *PuzzleSheet) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PuzzleSheet) SetId(v string) {
	o.Id = v
}

// GetInsertedAt returns the InsertedAt field value if set, zero value otherwise.
func (o *PuzzleSheet) GetInsertedAt() time.Time {
	if o == nil || IsNil(o.InsertedAt) {
		var ret time.Time
		return ret
	}
	return *o.InsertedAt
}

// GetInsertedAtOk returns a tuple with the InsertedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetInsertedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.InsertedAt) {
		return nil, false
	}
	return o.InsertedAt, true
}

// HasInsertedAt returns a boolean if a field has been set.
func (o *PuzzleSheet) HasInsertedAt() bool {
	if o != nil && !IsNil(o.InsertedAt) {
		return true
	}

	return false
}

// SetInsertedAt gets a reference to the given time.Time and assigns it to the InsertedAt field.
func (o *PuzzleSheet) SetInsertedAt(v time.Time) {
	o.InsertedAt = &v
}

// GetIsAdhocSheet returns the IsAdhocSheet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleSheet) GetIsAdhocSheet() bool {
	if o == nil || IsNil(o.IsAdhocSheet.Get()) {
		var ret bool
		return ret
	}
	return *o.IsAdhocSheet.Get()
}

// GetIsAdhocSheetOk returns a tuple with the IsAdhocSheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleSheet) GetIsAdhocSheetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsAdhocSheet.Get(), o.IsAdhocSheet.IsSet()
}

// HasIsAdhocSheet returns a boolean if a field has been set.
func (o *PuzzleSheet) HasIsAdhocSheet() bool {
	if o != nil && o.IsAdhocSheet.IsSet() {
		return true
	}

	return false
}

// SetIsAdhocSheet gets a reference to the given NullableBool and assigns it to the IsAdhocSheet field.
func (o *PuzzleSheet) SetIsAdhocSheet(v bool) {
	o.IsAdhocSheet.Set(&v)
}
// SetIsAdhocSheetNil sets the value for IsAdhocSheet to be an explicit nil
func (o *PuzzleSheet) SetIsAdhocSheetNil() {
	o.IsAdhocSheet.Set(nil)
}

// UnsetIsAdhocSheet ensures that no value is present for IsAdhocSheet, not even an explicit nil
func (o *PuzzleSheet) UnsetIsAdhocSheet() {
	o.IsAdhocSheet.Unset()
}

// GetIsCommunityQuestions returns the IsCommunityQuestions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleSheet) GetIsCommunityQuestions() bool {
	if o == nil || IsNil(o.IsCommunityQuestions.Get()) {
		var ret bool
		return ret
	}
	return *o.IsCommunityQuestions.Get()
}

// GetIsCommunityQuestionsOk returns a tuple with the IsCommunityQuestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleSheet) GetIsCommunityQuestionsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsCommunityQuestions.Get(), o.IsCommunityQuestions.IsSet()
}

// HasIsCommunityQuestions returns a boolean if a field has been set.
func (o *PuzzleSheet) HasIsCommunityQuestions() bool {
	if o != nil && o.IsCommunityQuestions.IsSet() {
		return true
	}

	return false
}

// SetIsCommunityQuestions gets a reference to the given NullableBool and assigns it to the IsCommunityQuestions field.
func (o *PuzzleSheet) SetIsCommunityQuestions(v bool) {
	o.IsCommunityQuestions.Set(&v)
}
// SetIsCommunityQuestionsNil sets the value for IsCommunityQuestions to be an explicit nil
func (o *PuzzleSheet) SetIsCommunityQuestionsNil() {
	o.IsCommunityQuestions.Set(nil)
}

// UnsetIsCommunityQuestions ensures that no value is present for IsCommunityQuestions, not even an explicit nil
func (o *PuzzleSheet) UnsetIsCommunityQuestions() {
	o.IsCommunityQuestions.Unset()
}

// GetName returns the Name field value
func (o *PuzzleSheet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PuzzleSheet) SetName(v string) {
	o.Name = v
}

// GetOwnerId returns the OwnerId field value
func (o *PuzzleSheet) GetOwnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetOwnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *PuzzleSheet) SetOwnerId(v string) {
	o.OwnerId = v
}

// GetPuzzles returns the Puzzles field value if set, zero value otherwise.
func (o *PuzzleSheet) GetPuzzles() []PuzzleBody {
	if o == nil || IsNil(o.Puzzles) {
		var ret []PuzzleBody
		return ret
	}
	return o.Puzzles
}

// GetPuzzlesOk returns a tuple with the Puzzles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetPuzzlesOk() ([]PuzzleBody, bool) {
	if o == nil || IsNil(o.Puzzles) {
		return nil, false
	}
	return o.Puzzles, true
}

// HasPuzzles returns a boolean if a field has been set.
func (o *PuzzleSheet) HasPuzzles() bool {
	if o != nil && !IsNil(o.Puzzles) {
		return true
	}

	return false
}

// SetPuzzles gets a reference to the given []PuzzleBody and assigns it to the Puzzles field.
func (o *PuzzleSheet) SetPuzzles(v []PuzzleBody) {
	o.Puzzles = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PuzzleSheet) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PuzzleSheet) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *PuzzleSheet) SetTags(v []string) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PuzzleSheet) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PuzzleSheet) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *PuzzleSheet) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVisibility returns the Visibility field value
func (o *PuzzleSheet) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *PuzzleSheet) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *PuzzleSheet) SetVisibility(v string) {
	o.Visibility = v
}

func (o PuzzleSheet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PuzzleSheet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.InsertedAt) {
		toSerialize["inserted_at"] = o.InsertedAt
	}
	if o.IsAdhocSheet.IsSet() {
		toSerialize["is_adhoc_sheet"] = o.IsAdhocSheet.Get()
	}
	if o.IsCommunityQuestions.IsSet() {
		toSerialize["is_community_questions"] = o.IsCommunityQuestions.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["owner_id"] = o.OwnerId
	if !IsNil(o.Puzzles) {
		toSerialize["puzzles"] = o.Puzzles
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["visibility"] = o.Visibility
	return toSerialize, nil
}

func (o *PuzzleSheet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"owner_id",
		"visibility",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPuzzleSheet := _PuzzleSheet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPuzzleSheet)

	if err != nil {
		return err
	}

	*o = PuzzleSheet(varPuzzleSheet)

	return err
}

type NullablePuzzleSheet struct {
	value *PuzzleSheet
	isSet bool
}

func (v NullablePuzzleSheet) Get() *PuzzleSheet {
	return v.value
}

func (v *NullablePuzzleSheet) Set(val *PuzzleSheet) {
	v.value = val
	v.isSet = true
}

func (v NullablePuzzleSheet) IsSet() bool {
	return v.isSet
}

func (v *NullablePuzzleSheet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePuzzleSheet(val *PuzzleSheet) *NullablePuzzleSheet {
	return &NullablePuzzleSheet{value: val, isSet: true}
}

func (v NullablePuzzleSheet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePuzzleSheet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


