/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainTournamentConfigurationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainTournamentConfigurationResponse{}

// DomainTournamentConfigurationResponse struct for DomainTournamentConfigurationResponse
type DomainTournamentConfigurationResponse struct {
	Data DomainTournamentConfiguration `json:"data"`
}

type _DomainTournamentConfigurationResponse DomainTournamentConfigurationResponse

// NewDomainTournamentConfigurationResponse instantiates a new DomainTournamentConfigurationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainTournamentConfigurationResponse(data DomainTournamentConfiguration) *DomainTournamentConfigurationResponse {
	this := DomainTournamentConfigurationResponse{}
	this.Data = data
	return &this
}

// NewDomainTournamentConfigurationResponseWithDefaults instantiates a new DomainTournamentConfigurationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainTournamentConfigurationResponseWithDefaults() *DomainTournamentConfigurationResponse {
	this := DomainTournamentConfigurationResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainTournamentConfigurationResponse) GetData() DomainTournamentConfiguration {
	if o == nil {
		var ret DomainTournamentConfiguration
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainTournamentConfigurationResponse) GetDataOk() (*DomainTournamentConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DomainTournamentConfigurationResponse) SetData(v DomainTournamentConfiguration) {
	o.Data = v
}

func (o DomainTournamentConfigurationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainTournamentConfigurationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DomainTournamentConfigurationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainTournamentConfigurationResponse := _DomainTournamentConfigurationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainTournamentConfigurationResponse)

	if err != nil {
		return err
	}

	*o = DomainTournamentConfigurationResponse(varDomainTournamentConfigurationResponse)

	return err
}

type NullableDomainTournamentConfigurationResponse struct {
	value *DomainTournamentConfigurationResponse
	isSet bool
}

func (v NullableDomainTournamentConfigurationResponse) Get() *DomainTournamentConfigurationResponse {
	return v.value
}

func (v *NullableDomainTournamentConfigurationResponse) Set(val *DomainTournamentConfigurationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainTournamentConfigurationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainTournamentConfigurationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainTournamentConfigurationResponse(val *DomainTournamentConfigurationResponse) *NullableDomainTournamentConfigurationResponse {
	return &NullableDomainTournamentConfigurationResponse{value: val, isSet: true}
}

func (v NullableDomainTournamentConfigurationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainTournamentConfigurationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


