/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainSubscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainSubscriptionResponse{}

// DomainSubscriptionResponse struct for DomainSubscriptionResponse
type DomainSubscriptionResponse struct {
	Data DomainSubscription `json:"data"`
}

type _DomainSubscriptionResponse DomainSubscriptionResponse

// NewDomainSubscriptionResponse instantiates a new DomainSubscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainSubscriptionResponse(data DomainSubscription) *DomainSubscriptionResponse {
	this := DomainSubscriptionResponse{}
	this.Data = data
	return &this
}

// NewDomainSubscriptionResponseWithDefaults instantiates a new DomainSubscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainSubscriptionResponseWithDefaults() *DomainSubscriptionResponse {
	this := DomainSubscriptionResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainSubscriptionResponse) GetData() DomainSubscription {
	if o == nil {
		var ret DomainSubscription
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainSubscriptionResponse) GetDataOk() (*DomainSubscription, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DomainSubscriptionResponse) SetData(v DomainSubscription) {
	o.Data = v
}

func (o DomainSubscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainSubscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DomainSubscriptionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainSubscriptionResponse := _DomainSubscriptionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainSubscriptionResponse)

	if err != nil {
		return err
	}

	*o = DomainSubscriptionResponse(varDomainSubscriptionResponse)

	return err
}

type NullableDomainSubscriptionResponse struct {
	value *DomainSubscriptionResponse
	isSet bool
}

func (v NullableDomainSubscriptionResponse) Get() *DomainSubscriptionResponse {
	return v.value
}

func (v *NullableDomainSubscriptionResponse) Set(val *DomainSubscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainSubscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainSubscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainSubscriptionResponse(val *DomainSubscriptionResponse) *NullableDomainSubscriptionResponse {
	return &NullableDomainSubscriptionResponse{value: val, isSet: true}
}

func (v NullableDomainSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainSubscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


