/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the HandlerCreatePlatformIdentityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerCreatePlatformIdentityRequest{}

// HandlerCreatePlatformIdentityRequest struct for HandlerCreatePlatformIdentityRequest
type HandlerCreatePlatformIdentityRequest struct {
	Company *string `json:"company,omitempty"`
	// CountryCode is an optional ISO 3166-1 alpha-2 region the tenant supplies to scope geo-eligibility on the fan's contests and channels. Empty is permitted — geo queries tolerate it by returning the wider unscoped result. Added in slice 22.6 / uman#107 (Member vestige cleanup).
	CountryCode *string `json:"country_code,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	HeaderImageUrl *string `json:"header_image_url,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	ProfilePic *string `json:"profile_pic,omitempty"`
}

// NewHandlerCreatePlatformIdentityRequest instantiates a new HandlerCreatePlatformIdentityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerCreatePlatformIdentityRequest() *HandlerCreatePlatformIdentityRequest {
	this := HandlerCreatePlatformIdentityRequest{}
	return &this
}

// NewHandlerCreatePlatformIdentityRequestWithDefaults instantiates a new HandlerCreatePlatformIdentityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerCreatePlatformIdentityRequestWithDefaults() *HandlerCreatePlatformIdentityRequest {
	this := HandlerCreatePlatformIdentityRequest{}
	return &this
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *HandlerCreatePlatformIdentityRequest) SetCompany(v string) {
	o.Company = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *HandlerCreatePlatformIdentityRequest) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *HandlerCreatePlatformIdentityRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *HandlerCreatePlatformIdentityRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetHeaderImageUrl returns the HeaderImageUrl field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetHeaderImageUrl() string {
	if o == nil || IsNil(o.HeaderImageUrl) {
		var ret string
		return ret
	}
	return *o.HeaderImageUrl
}

// GetHeaderImageUrlOk returns a tuple with the HeaderImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetHeaderImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.HeaderImageUrl) {
		return nil, false
	}
	return o.HeaderImageUrl, true
}

// HasHeaderImageUrl returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasHeaderImageUrl() bool {
	if o != nil && !IsNil(o.HeaderImageUrl) {
		return true
	}

	return false
}

// SetHeaderImageUrl gets a reference to the given string and assigns it to the HeaderImageUrl field.
func (o *HandlerCreatePlatformIdentityRequest) SetHeaderImageUrl(v string) {
	o.HeaderImageUrl = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *HandlerCreatePlatformIdentityRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *HandlerCreatePlatformIdentityRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetProfilePic returns the ProfilePic field value if set, zero value otherwise.
func (o *HandlerCreatePlatformIdentityRequest) GetProfilePic() string {
	if o == nil || IsNil(o.ProfilePic) {
		var ret string
		return ret
	}
	return *o.ProfilePic
}

// GetProfilePicOk returns a tuple with the ProfilePic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformIdentityRequest) GetProfilePicOk() (*string, bool) {
	if o == nil || IsNil(o.ProfilePic) {
		return nil, false
	}
	return o.ProfilePic, true
}

// HasProfilePic returns a boolean if a field has been set.
func (o *HandlerCreatePlatformIdentityRequest) HasProfilePic() bool {
	if o != nil && !IsNil(o.ProfilePic) {
		return true
	}

	return false
}

// SetProfilePic gets a reference to the given string and assigns it to the ProfilePic field.
func (o *HandlerCreatePlatformIdentityRequest) SetProfilePic(v string) {
	o.ProfilePic = &v
}

func (o HandlerCreatePlatformIdentityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerCreatePlatformIdentityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.HeaderImageUrl) {
		toSerialize["header_image_url"] = o.HeaderImageUrl
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.ProfilePic) {
		toSerialize["profile_pic"] = o.ProfilePic
	}
	return toSerialize, nil
}

type NullableHandlerCreatePlatformIdentityRequest struct {
	value *HandlerCreatePlatformIdentityRequest
	isSet bool
}

func (v NullableHandlerCreatePlatformIdentityRequest) Get() *HandlerCreatePlatformIdentityRequest {
	return v.value
}

func (v *NullableHandlerCreatePlatformIdentityRequest) Set(val *HandlerCreatePlatformIdentityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerCreatePlatformIdentityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerCreatePlatformIdentityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerCreatePlatformIdentityRequest(val *HandlerCreatePlatformIdentityRequest) *NullableHandlerCreatePlatformIdentityRequest {
	return &NullableHandlerCreatePlatformIdentityRequest{value: val, isSet: true}
}

func (v NullableHandlerCreatePlatformIdentityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerCreatePlatformIdentityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


