/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HandlerCreatePlatformVenueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerCreatePlatformVenueRequest{}

// HandlerCreatePlatformVenueRequest struct for HandlerCreatePlatformVenueRequest
type HandlerCreatePlatformVenueRequest struct {
	ExternalRef *string `json:"external_ref,omitempty"`
	Name string `json:"name"`
	Type string `json:"type"`
}

type _HandlerCreatePlatformVenueRequest HandlerCreatePlatformVenueRequest

// NewHandlerCreatePlatformVenueRequest instantiates a new HandlerCreatePlatformVenueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerCreatePlatformVenueRequest(name string, type_ string) *HandlerCreatePlatformVenueRequest {
	this := HandlerCreatePlatformVenueRequest{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewHandlerCreatePlatformVenueRequestWithDefaults instantiates a new HandlerCreatePlatformVenueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerCreatePlatformVenueRequestWithDefaults() *HandlerCreatePlatformVenueRequest {
	this := HandlerCreatePlatformVenueRequest{}
	return &this
}

// GetExternalRef returns the ExternalRef field value if set, zero value otherwise.
func (o *HandlerCreatePlatformVenueRequest) GetExternalRef() string {
	if o == nil || IsNil(o.ExternalRef) {
		var ret string
		return ret
	}
	return *o.ExternalRef
}

// GetExternalRefOk returns a tuple with the ExternalRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformVenueRequest) GetExternalRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalRef) {
		return nil, false
	}
	return o.ExternalRef, true
}

// HasExternalRef returns a boolean if a field has been set.
func (o *HandlerCreatePlatformVenueRequest) HasExternalRef() bool {
	if o != nil && !IsNil(o.ExternalRef) {
		return true
	}

	return false
}

// SetExternalRef gets a reference to the given string and assigns it to the ExternalRef field.
func (o *HandlerCreatePlatformVenueRequest) SetExternalRef(v string) {
	o.ExternalRef = &v
}

// GetName returns the Name field value
func (o *HandlerCreatePlatformVenueRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformVenueRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HandlerCreatePlatformVenueRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *HandlerCreatePlatformVenueRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HandlerCreatePlatformVenueRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HandlerCreatePlatformVenueRequest) SetType(v string) {
	o.Type = v
}

func (o HandlerCreatePlatformVenueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerCreatePlatformVenueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalRef) {
		toSerialize["external_ref"] = o.ExternalRef
	}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *HandlerCreatePlatformVenueRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHandlerCreatePlatformVenueRequest := _HandlerCreatePlatformVenueRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHandlerCreatePlatformVenueRequest)

	if err != nil {
		return err
	}

	*o = HandlerCreatePlatformVenueRequest(varHandlerCreatePlatformVenueRequest)

	return err
}

type NullableHandlerCreatePlatformVenueRequest struct {
	value *HandlerCreatePlatformVenueRequest
	isSet bool
}

func (v NullableHandlerCreatePlatformVenueRequest) Get() *HandlerCreatePlatformVenueRequest {
	return v.value
}

func (v *NullableHandlerCreatePlatformVenueRequest) Set(val *HandlerCreatePlatformVenueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerCreatePlatformVenueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerCreatePlatformVenueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerCreatePlatformVenueRequest(val *HandlerCreatePlatformVenueRequest) *NullableHandlerCreatePlatformVenueRequest {
	return &NullableHandlerCreatePlatformVenueRequest{value: val, isSet: true}
}

func (v NullableHandlerCreatePlatformVenueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerCreatePlatformVenueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


