/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainSponsorshipAgreement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainSponsorshipAgreement{}

// DomainSponsorshipAgreement struct for DomainSponsorshipAgreement
type DomainSponsorshipAgreement struct {
	AcceptedAt *string `json:"accepted_at,omitempty"`
	Amount *DomainAmount `json:"amount,omitempty"`
	BrandingTerms *string `json:"branding_terms,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Deadline *string `json:"deadline,omitempty"`
	Id *string `json:"id,omitempty"`
	// For package-based agreements
	PackageId *string `json:"package_id,omitempty"`
	SponsorshipId *string `json:"sponsorship_id,omitempty"`
	State *string `json:"state,omitempty"`
	TermsSnapshot []DomainSponsorshipTermSnapshot `json:"terms_snapshot,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewDomainSponsorshipAgreement instantiates a new DomainSponsorshipAgreement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainSponsorshipAgreement() *DomainSponsorshipAgreement {
	this := DomainSponsorshipAgreement{}
	return &this
}

// NewDomainSponsorshipAgreementWithDefaults instantiates a new DomainSponsorshipAgreement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainSponsorshipAgreementWithDefaults() *DomainSponsorshipAgreement {
	this := DomainSponsorshipAgreement{}
	return &this
}

// GetAcceptedAt returns the AcceptedAt field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetAcceptedAt() string {
	if o == nil || IsNil(o.AcceptedAt) {
		var ret string
		return ret
	}
	return *o.AcceptedAt
}

// GetAcceptedAtOk returns a tuple with the AcceptedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetAcceptedAtOk() (*string, bool) {
	if o == nil || IsNil(o.AcceptedAt) {
		return nil, false
	}
	return o.AcceptedAt, true
}

// HasAcceptedAt returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasAcceptedAt() bool {
	if o != nil && !IsNil(o.AcceptedAt) {
		return true
	}

	return false
}

// SetAcceptedAt gets a reference to the given string and assigns it to the AcceptedAt field.
func (o *DomainSponsorshipAgreement) SetAcceptedAt(v string) {
	o.AcceptedAt = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetAmount() DomainAmount {
	if o == nil || IsNil(o.Amount) {
		var ret DomainAmount
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetAmountOk() (*DomainAmount, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given DomainAmount and assigns it to the Amount field.
func (o *DomainSponsorshipAgreement) SetAmount(v DomainAmount) {
	o.Amount = &v
}

// GetBrandingTerms returns the BrandingTerms field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetBrandingTerms() string {
	if o == nil || IsNil(o.BrandingTerms) {
		var ret string
		return ret
	}
	return *o.BrandingTerms
}

// GetBrandingTermsOk returns a tuple with the BrandingTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetBrandingTermsOk() (*string, bool) {
	if o == nil || IsNil(o.BrandingTerms) {
		return nil, false
	}
	return o.BrandingTerms, true
}

// HasBrandingTerms returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasBrandingTerms() bool {
	if o != nil && !IsNil(o.BrandingTerms) {
		return true
	}

	return false
}

// SetBrandingTerms gets a reference to the given string and assigns it to the BrandingTerms field.
func (o *DomainSponsorshipAgreement) SetBrandingTerms(v string) {
	o.BrandingTerms = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DomainSponsorshipAgreement) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetDeadline() string {
	if o == nil || IsNil(o.Deadline) {
		var ret string
		return ret
	}
	return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetDeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Deadline) {
		return nil, false
	}
	return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasDeadline() bool {
	if o != nil && !IsNil(o.Deadline) {
		return true
	}

	return false
}

// SetDeadline gets a reference to the given string and assigns it to the Deadline field.
func (o *DomainSponsorshipAgreement) SetDeadline(v string) {
	o.Deadline = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DomainSponsorshipAgreement) SetId(v string) {
	o.Id = &v
}

// GetPackageId returns the PackageId field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetPackageId() string {
	if o == nil || IsNil(o.PackageId) {
		var ret string
		return ret
	}
	return *o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetPackageIdOk() (*string, bool) {
	if o == nil || IsNil(o.PackageId) {
		return nil, false
	}
	return o.PackageId, true
}

// HasPackageId returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasPackageId() bool {
	if o != nil && !IsNil(o.PackageId) {
		return true
	}

	return false
}

// SetPackageId gets a reference to the given string and assigns it to the PackageId field.
func (o *DomainSponsorshipAgreement) SetPackageId(v string) {
	o.PackageId = &v
}

// GetSponsorshipId returns the SponsorshipId field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetSponsorshipId() string {
	if o == nil || IsNil(o.SponsorshipId) {
		var ret string
		return ret
	}
	return *o.SponsorshipId
}

// GetSponsorshipIdOk returns a tuple with the SponsorshipId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetSponsorshipIdOk() (*string, bool) {
	if o == nil || IsNil(o.SponsorshipId) {
		return nil, false
	}
	return o.SponsorshipId, true
}

// HasSponsorshipId returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasSponsorshipId() bool {
	if o != nil && !IsNil(o.SponsorshipId) {
		return true
	}

	return false
}

// SetSponsorshipId gets a reference to the given string and assigns it to the SponsorshipId field.
func (o *DomainSponsorshipAgreement) SetSponsorshipId(v string) {
	o.SponsorshipId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *DomainSponsorshipAgreement) SetState(v string) {
	o.State = &v
}

// GetTermsSnapshot returns the TermsSnapshot field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetTermsSnapshot() []DomainSponsorshipTermSnapshot {
	if o == nil || IsNil(o.TermsSnapshot) {
		var ret []DomainSponsorshipTermSnapshot
		return ret
	}
	return o.TermsSnapshot
}

// GetTermsSnapshotOk returns a tuple with the TermsSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetTermsSnapshotOk() ([]DomainSponsorshipTermSnapshot, bool) {
	if o == nil || IsNil(o.TermsSnapshot) {
		return nil, false
	}
	return o.TermsSnapshot, true
}

// HasTermsSnapshot returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasTermsSnapshot() bool {
	if o != nil && !IsNil(o.TermsSnapshot) {
		return true
	}

	return false
}

// SetTermsSnapshot gets a reference to the given []DomainSponsorshipTermSnapshot and assigns it to the TermsSnapshot field.
func (o *DomainSponsorshipAgreement) SetTermsSnapshot(v []DomainSponsorshipTermSnapshot) {
	o.TermsSnapshot = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DomainSponsorshipAgreement) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipAgreement) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DomainSponsorshipAgreement) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *DomainSponsorshipAgreement) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o DomainSponsorshipAgreement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainSponsorshipAgreement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcceptedAt) {
		toSerialize["accepted_at"] = o.AcceptedAt
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.BrandingTerms) {
		toSerialize["branding_terms"] = o.BrandingTerms
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Deadline) {
		toSerialize["deadline"] = o.Deadline
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PackageId) {
		toSerialize["package_id"] = o.PackageId
	}
	if !IsNil(o.SponsorshipId) {
		toSerialize["sponsorship_id"] = o.SponsorshipId
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.TermsSnapshot) {
		toSerialize["terms_snapshot"] = o.TermsSnapshot
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableDomainSponsorshipAgreement struct {
	value *DomainSponsorshipAgreement
	isSet bool
}

func (v NullableDomainSponsorshipAgreement) Get() *DomainSponsorshipAgreement {
	return v.value
}

func (v *NullableDomainSponsorshipAgreement) Set(val *DomainSponsorshipAgreement) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainSponsorshipAgreement) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainSponsorshipAgreement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainSponsorshipAgreement(val *DomainSponsorshipAgreement) *NullableDomainSponsorshipAgreement {
	return &NullableDomainSponsorshipAgreement{value: val, isSet: true}
}

func (v NullableDomainSponsorshipAgreement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainSponsorshipAgreement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


