/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAnalyticsOverview200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnalyticsOverview200Response{}

// GetAnalyticsOverview200Response struct for GetAnalyticsOverview200Response
type GetAnalyticsOverview200Response struct {
	Data DomainStatsOverview `json:"data"`
}

type _GetAnalyticsOverview200Response GetAnalyticsOverview200Response

// NewGetAnalyticsOverview200Response instantiates a new GetAnalyticsOverview200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticsOverview200Response(data DomainStatsOverview) *GetAnalyticsOverview200Response {
	this := GetAnalyticsOverview200Response{}
	this.Data = data
	return &this
}

// NewGetAnalyticsOverview200ResponseWithDefaults instantiates a new GetAnalyticsOverview200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticsOverview200ResponseWithDefaults() *GetAnalyticsOverview200Response {
	this := GetAnalyticsOverview200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetAnalyticsOverview200Response) GetData() DomainStatsOverview {
	if o == nil {
		var ret DomainStatsOverview
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticsOverview200Response) GetDataOk() (*DomainStatsOverview, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAnalyticsOverview200Response) SetData(v DomainStatsOverview) {
	o.Data = v
}

func (o GetAnalyticsOverview200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnalyticsOverview200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetAnalyticsOverview200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAnalyticsOverview200Response := _GetAnalyticsOverview200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAnalyticsOverview200Response)

	if err != nil {
		return err
	}

	*o = GetAnalyticsOverview200Response(varGetAnalyticsOverview200Response)

	return err
}

type NullableGetAnalyticsOverview200Response struct {
	value *GetAnalyticsOverview200Response
	isSet bool
}

func (v NullableGetAnalyticsOverview200Response) Get() *GetAnalyticsOverview200Response {
	return v.value
}

func (v *NullableGetAnalyticsOverview200Response) Set(val *GetAnalyticsOverview200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticsOverview200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticsOverview200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticsOverview200Response(val *GetAnalyticsOverview200Response) *NullableGetAnalyticsOverview200Response {
	return &NullableGetAnalyticsOverview200Response{value: val, isSet: true}
}

func (v NullableGetAnalyticsOverview200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticsOverview200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


