/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the DomainSubmissionZoneConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainSubmissionZoneConfiguration{}

// DomainSubmissionZoneConfiguration struct for DomainSubmissionZoneConfiguration
type DomainSubmissionZoneConfiguration struct {
	BlueZone *DomainSubmissionZone `json:"blue_zone,omitempty"`
	ContestId *string `json:"contest_id,omitempty"`
	GreenZone *DomainSubmissionZone `json:"green_zone,omitempty"`
	Id *string `json:"id,omitempty"`
	OrangeZone *DomainSubmissionZone `json:"orange_zone,omitempty"`
	RedZone *DomainSubmissionZone `json:"red_zone,omitempty"`
}

// NewDomainSubmissionZoneConfiguration instantiates a new DomainSubmissionZoneConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainSubmissionZoneConfiguration() *DomainSubmissionZoneConfiguration {
	this := DomainSubmissionZoneConfiguration{}
	return &this
}

// NewDomainSubmissionZoneConfigurationWithDefaults instantiates a new DomainSubmissionZoneConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainSubmissionZoneConfigurationWithDefaults() *DomainSubmissionZoneConfiguration {
	this := DomainSubmissionZoneConfiguration{}
	return &this
}

// GetBlueZone returns the BlueZone field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetBlueZone() DomainSubmissionZone {
	if o == nil || IsNil(o.BlueZone) {
		var ret DomainSubmissionZone
		return ret
	}
	return *o.BlueZone
}

// GetBlueZoneOk returns a tuple with the BlueZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetBlueZoneOk() (*DomainSubmissionZone, bool) {
	if o == nil || IsNil(o.BlueZone) {
		return nil, false
	}
	return o.BlueZone, true
}

// HasBlueZone returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasBlueZone() bool {
	if o != nil && !IsNil(o.BlueZone) {
		return true
	}

	return false
}

// SetBlueZone gets a reference to the given DomainSubmissionZone and assigns it to the BlueZone field.
func (o *DomainSubmissionZoneConfiguration) SetBlueZone(v DomainSubmissionZone) {
	o.BlueZone = &v
}

// GetContestId returns the ContestId field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetContestId() string {
	if o == nil || IsNil(o.ContestId) {
		var ret string
		return ret
	}
	return *o.ContestId
}

// GetContestIdOk returns a tuple with the ContestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetContestIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContestId) {
		return nil, false
	}
	return o.ContestId, true
}

// HasContestId returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasContestId() bool {
	if o != nil && !IsNil(o.ContestId) {
		return true
	}

	return false
}

// SetContestId gets a reference to the given string and assigns it to the ContestId field.
func (o *DomainSubmissionZoneConfiguration) SetContestId(v string) {
	o.ContestId = &v
}

// GetGreenZone returns the GreenZone field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetGreenZone() DomainSubmissionZone {
	if o == nil || IsNil(o.GreenZone) {
		var ret DomainSubmissionZone
		return ret
	}
	return *o.GreenZone
}

// GetGreenZoneOk returns a tuple with the GreenZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetGreenZoneOk() (*DomainSubmissionZone, bool) {
	if o == nil || IsNil(o.GreenZone) {
		return nil, false
	}
	return o.GreenZone, true
}

// HasGreenZone returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasGreenZone() bool {
	if o != nil && !IsNil(o.GreenZone) {
		return true
	}

	return false
}

// SetGreenZone gets a reference to the given DomainSubmissionZone and assigns it to the GreenZone field.
func (o *DomainSubmissionZoneConfiguration) SetGreenZone(v DomainSubmissionZone) {
	o.GreenZone = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DomainSubmissionZoneConfiguration) SetId(v string) {
	o.Id = &v
}

// GetOrangeZone returns the OrangeZone field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetOrangeZone() DomainSubmissionZone {
	if o == nil || IsNil(o.OrangeZone) {
		var ret DomainSubmissionZone
		return ret
	}
	return *o.OrangeZone
}

// GetOrangeZoneOk returns a tuple with the OrangeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetOrangeZoneOk() (*DomainSubmissionZone, bool) {
	if o == nil || IsNil(o.OrangeZone) {
		return nil, false
	}
	return o.OrangeZone, true
}

// HasOrangeZone returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasOrangeZone() bool {
	if o != nil && !IsNil(o.OrangeZone) {
		return true
	}

	return false
}

// SetOrangeZone gets a reference to the given DomainSubmissionZone and assigns it to the OrangeZone field.
func (o *DomainSubmissionZoneConfiguration) SetOrangeZone(v DomainSubmissionZone) {
	o.OrangeZone = &v
}

// GetRedZone returns the RedZone field value if set, zero value otherwise.
func (o *DomainSubmissionZoneConfiguration) GetRedZone() DomainSubmissionZone {
	if o == nil || IsNil(o.RedZone) {
		var ret DomainSubmissionZone
		return ret
	}
	return *o.RedZone
}

// GetRedZoneOk returns a tuple with the RedZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSubmissionZoneConfiguration) GetRedZoneOk() (*DomainSubmissionZone, bool) {
	if o == nil || IsNil(o.RedZone) {
		return nil, false
	}
	return o.RedZone, true
}

// HasRedZone returns a boolean if a field has been set.
func (o *DomainSubmissionZoneConfiguration) HasRedZone() bool {
	if o != nil && !IsNil(o.RedZone) {
		return true
	}

	return false
}

// SetRedZone gets a reference to the given DomainSubmissionZone and assigns it to the RedZone field.
func (o *DomainSubmissionZoneConfiguration) SetRedZone(v DomainSubmissionZone) {
	o.RedZone = &v
}

func (o DomainSubmissionZoneConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainSubmissionZoneConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlueZone) {
		toSerialize["blue_zone"] = o.BlueZone
	}
	if !IsNil(o.ContestId) {
		toSerialize["contest_id"] = o.ContestId
	}
	if !IsNil(o.GreenZone) {
		toSerialize["green_zone"] = o.GreenZone
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.OrangeZone) {
		toSerialize["orange_zone"] = o.OrangeZone
	}
	if !IsNil(o.RedZone) {
		toSerialize["red_zone"] = o.RedZone
	}
	return toSerialize, nil
}

type NullableDomainSubmissionZoneConfiguration struct {
	value *DomainSubmissionZoneConfiguration
	isSet bool
}

func (v NullableDomainSubmissionZoneConfiguration) Get() *DomainSubmissionZoneConfiguration {
	return v.value
}

func (v *NullableDomainSubmissionZoneConfiguration) Set(val *DomainSubmissionZoneConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainSubmissionZoneConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainSubmissionZoneConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainSubmissionZoneConfiguration(val *DomainSubmissionZoneConfiguration) *NullableDomainSubmissionZoneConfiguration {
	return &NullableDomainSubmissionZoneConfiguration{value: val, isSet: true}
}

func (v NullableDomainSubmissionZoneConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainSubmissionZoneConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


