/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainTiming type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainTiming{}

// DomainTiming struct for DomainTiming
type DomainTiming struct {
	EndAt string `json:"end_at"`
	EnrollBy string `json:"enroll_by"`
	StartAt string `json:"start_at"`
}

type _DomainTiming DomainTiming

// NewDomainTiming instantiates a new DomainTiming object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainTiming(endAt string, enrollBy string, startAt string) *DomainTiming {
	this := DomainTiming{}
	this.EndAt = endAt
	this.EnrollBy = enrollBy
	this.StartAt = startAt
	return &this
}

// NewDomainTimingWithDefaults instantiates a new DomainTiming object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainTimingWithDefaults() *DomainTiming {
	this := DomainTiming{}
	return &this
}

// GetEndAt returns the EndAt field value
func (o *DomainTiming) GetEndAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value
// and a boolean to check if the value has been set.
func (o *DomainTiming) GetEndAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndAt, true
}

// SetEndAt sets field value
func (o *DomainTiming) SetEndAt(v string) {
	o.EndAt = v
}

// GetEnrollBy returns the EnrollBy field value
func (o *DomainTiming) GetEnrollBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnrollBy
}

// GetEnrollByOk returns a tuple with the EnrollBy field value
// and a boolean to check if the value has been set.
func (o *DomainTiming) GetEnrollByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnrollBy, true
}

// SetEnrollBy sets field value
func (o *DomainTiming) SetEnrollBy(v string) {
	o.EnrollBy = v
}

// GetStartAt returns the StartAt field value
func (o *DomainTiming) GetStartAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *DomainTiming) GetStartAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *DomainTiming) SetStartAt(v string) {
	o.StartAt = v
}

func (o DomainTiming) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainTiming) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["end_at"] = o.EndAt
	toSerialize["enroll_by"] = o.EnrollBy
	toSerialize["start_at"] = o.StartAt
	return toSerialize, nil
}

func (o *DomainTiming) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"end_at",
		"enroll_by",
		"start_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainTiming := _DomainTiming{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainTiming)

	if err != nil {
		return err
	}

	*o = DomainTiming(varDomainTiming)

	return err
}

type NullableDomainTiming struct {
	value *DomainTiming
	isSet bool
}

func (v NullableDomainTiming) Get() *DomainTiming {
	return v.value
}

func (v *NullableDomainTiming) Set(val *DomainTiming) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainTiming) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainTiming) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainTiming(val *DomainTiming) *NullableDomainTiming {
	return &NullableDomainTiming{value: val, isSet: true}
}

func (v NullableDomainTiming) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainTiming) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


