/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainSponsorshipTermListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainSponsorshipTermListResponse{}

// DomainSponsorshipTermListResponse struct for DomainSponsorshipTermListResponse
type DomainSponsorshipTermListResponse struct {
	Data []DomainSponsorshipTerm `json:"data"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

type _DomainSponsorshipTermListResponse DomainSponsorshipTermListResponse

// NewDomainSponsorshipTermListResponse instantiates a new DomainSponsorshipTermListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainSponsorshipTermListResponse(data []DomainSponsorshipTerm) *DomainSponsorshipTermListResponse {
	this := DomainSponsorshipTermListResponse{}
	this.Data = data
	return &this
}

// NewDomainSponsorshipTermListResponseWithDefaults instantiates a new DomainSponsorshipTermListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainSponsorshipTermListResponseWithDefaults() *DomainSponsorshipTermListResponse {
	this := DomainSponsorshipTermListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainSponsorshipTermListResponse) GetData() []DomainSponsorshipTerm {
	if o == nil {
		var ret []DomainSponsorshipTerm
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipTermListResponse) GetDataOk() ([]DomainSponsorshipTerm, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DomainSponsorshipTermListResponse) SetData(v []DomainSponsorshipTerm) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DomainSponsorshipTermListResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainSponsorshipTermListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DomainSponsorshipTermListResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *DomainSponsorshipTermListResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o DomainSponsorshipTermListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainSponsorshipTermListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

func (o *DomainSponsorshipTermListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainSponsorshipTermListResponse := _DomainSponsorshipTermListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainSponsorshipTermListResponse)

	if err != nil {
		return err
	}

	*o = DomainSponsorshipTermListResponse(varDomainSponsorshipTermListResponse)

	return err
}

type NullableDomainSponsorshipTermListResponse struct {
	value *DomainSponsorshipTermListResponse
	isSet bool
}

func (v NullableDomainSponsorshipTermListResponse) Get() *DomainSponsorshipTermListResponse {
	return v.value
}

func (v *NullableDomainSponsorshipTermListResponse) Set(val *DomainSponsorshipTermListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainSponsorshipTermListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainSponsorshipTermListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainSponsorshipTermListResponse(val *DomainSponsorshipTermListResponse) *NullableDomainSponsorshipTermListResponse {
	return &NullableDomainSponsorshipTermListResponse{value: val, isSet: true}
}

func (v NullableDomainSponsorshipTermListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainSponsorshipTermListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


