/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainContestGroupsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainContestGroupsResponse{}

// DomainContestGroupsResponse struct for DomainContestGroupsResponse
type DomainContestGroupsResponse struct {
	Data DomainContestGroups `json:"data"`
}

type _DomainContestGroupsResponse DomainContestGroupsResponse

// NewDomainContestGroupsResponse instantiates a new DomainContestGroupsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainContestGroupsResponse(data DomainContestGroups) *DomainContestGroupsResponse {
	this := DomainContestGroupsResponse{}
	this.Data = data
	return &this
}

// NewDomainContestGroupsResponseWithDefaults instantiates a new DomainContestGroupsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainContestGroupsResponseWithDefaults() *DomainContestGroupsResponse {
	this := DomainContestGroupsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainContestGroupsResponse) GetData() DomainContestGroups {
	if o == nil {
		var ret DomainContestGroups
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainContestGroupsResponse) GetDataOk() (*DomainContestGroups, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DomainContestGroupsResponse) SetData(v DomainContestGroups) {
	o.Data = v
}

func (o DomainContestGroupsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainContestGroupsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DomainContestGroupsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainContestGroupsResponse := _DomainContestGroupsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainContestGroupsResponse)

	if err != nil {
		return err
	}

	*o = DomainContestGroupsResponse(varDomainContestGroupsResponse)

	return err
}

type NullableDomainContestGroupsResponse struct {
	value *DomainContestGroupsResponse
	isSet bool
}

func (v NullableDomainContestGroupsResponse) Get() *DomainContestGroupsResponse {
	return v.value
}

func (v *NullableDomainContestGroupsResponse) Set(val *DomainContestGroupsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainContestGroupsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainContestGroupsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainContestGroupsResponse(val *DomainContestGroupsResponse) *NullableDomainContestGroupsResponse {
	return &NullableDomainContestGroupsResponse{value: val, isSet: true}
}

func (v NullableDomainContestGroupsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainContestGroupsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


