/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the HandlerMatchupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerMatchupResponse{}

// HandlerMatchupResponse struct for HandlerMatchupResponse
type HandlerMatchupResponse struct {
	Matchup *HandlerServedMatchup `json:"matchup,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewHandlerMatchupResponse instantiates a new HandlerMatchupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerMatchupResponse() *HandlerMatchupResponse {
	this := HandlerMatchupResponse{}
	return &this
}

// NewHandlerMatchupResponseWithDefaults instantiates a new HandlerMatchupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerMatchupResponseWithDefaults() *HandlerMatchupResponse {
	this := HandlerMatchupResponse{}
	return &this
}

// GetMatchup returns the Matchup field value if set, zero value otherwise.
func (o *HandlerMatchupResponse) GetMatchup() HandlerServedMatchup {
	if o == nil || IsNil(o.Matchup) {
		var ret HandlerServedMatchup
		return ret
	}
	return *o.Matchup
}

// GetMatchupOk returns a tuple with the Matchup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerMatchupResponse) GetMatchupOk() (*HandlerServedMatchup, bool) {
	if o == nil || IsNil(o.Matchup) {
		return nil, false
	}
	return o.Matchup, true
}

// HasMatchup returns a boolean if a field has been set.
func (o *HandlerMatchupResponse) HasMatchup() bool {
	if o != nil && !IsNil(o.Matchup) {
		return true
	}

	return false
}

// SetMatchup gets a reference to the given HandlerServedMatchup and assigns it to the Matchup field.
func (o *HandlerMatchupResponse) SetMatchup(v HandlerServedMatchup) {
	o.Matchup = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *HandlerMatchupResponse) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerMatchupResponse) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *HandlerMatchupResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *HandlerMatchupResponse) SetReason(v string) {
	o.Reason = &v
}

func (o HandlerMatchupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerMatchupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Matchup) {
		toSerialize["matchup"] = o.Matchup
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableHandlerMatchupResponse struct {
	value *HandlerMatchupResponse
	isSet bool
}

func (v NullableHandlerMatchupResponse) Get() *HandlerMatchupResponse {
	return v.value
}

func (v *NullableHandlerMatchupResponse) Set(val *HandlerMatchupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerMatchupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerMatchupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerMatchupResponse(val *HandlerMatchupResponse) *NullableHandlerMatchupResponse {
	return &NullableHandlerMatchupResponse{value: val, isSet: true}
}

func (v NullableHandlerMatchupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerMatchupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


