/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainJurorAssignmentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainJurorAssignmentListResponse{}

// DomainJurorAssignmentListResponse struct for DomainJurorAssignmentListResponse
type DomainJurorAssignmentListResponse struct {
	Data []DomainJurorAssignment `json:"data"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

type _DomainJurorAssignmentListResponse DomainJurorAssignmentListResponse

// NewDomainJurorAssignmentListResponse instantiates a new DomainJurorAssignmentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainJurorAssignmentListResponse(data []DomainJurorAssignment) *DomainJurorAssignmentListResponse {
	this := DomainJurorAssignmentListResponse{}
	this.Data = data
	return &this
}

// NewDomainJurorAssignmentListResponseWithDefaults instantiates a new DomainJurorAssignmentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainJurorAssignmentListResponseWithDefaults() *DomainJurorAssignmentListResponse {
	this := DomainJurorAssignmentListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *DomainJurorAssignmentListResponse) GetData() []DomainJurorAssignment {
	if o == nil {
		var ret []DomainJurorAssignment
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DomainJurorAssignmentListResponse) GetDataOk() ([]DomainJurorAssignment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DomainJurorAssignmentListResponse) SetData(v []DomainJurorAssignment) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *DomainJurorAssignmentListResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainJurorAssignmentListResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *DomainJurorAssignmentListResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *DomainJurorAssignmentListResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o DomainJurorAssignmentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainJurorAssignmentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

func (o *DomainJurorAssignmentListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainJurorAssignmentListResponse := _DomainJurorAssignmentListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainJurorAssignmentListResponse)

	if err != nil {
		return err
	}

	*o = DomainJurorAssignmentListResponse(varDomainJurorAssignmentListResponse)

	return err
}

type NullableDomainJurorAssignmentListResponse struct {
	value *DomainJurorAssignmentListResponse
	isSet bool
}

func (v NullableDomainJurorAssignmentListResponse) Get() *DomainJurorAssignmentListResponse {
	return v.value
}

func (v *NullableDomainJurorAssignmentListResponse) Set(val *DomainJurorAssignmentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainJurorAssignmentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainJurorAssignmentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainJurorAssignmentListResponse(val *DomainJurorAssignmentListResponse) *NullableDomainJurorAssignmentListResponse {
	return &NullableDomainJurorAssignmentListResponse{value: val, isSet: true}
}

func (v NullableDomainJurorAssignmentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainJurorAssignmentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


