/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the PuzzleWebV2UserEventsControllerIndex200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PuzzleWebV2UserEventsControllerIndex200Response{}

// PuzzleWebV2UserEventsControllerIndex200Response struct for PuzzleWebV2UserEventsControllerIndex200Response
type PuzzleWebV2UserEventsControllerIndex200Response struct {
	Data []Event `json:"data,omitempty"`
}

// NewPuzzleWebV2UserEventsControllerIndex200Response instantiates a new PuzzleWebV2UserEventsControllerIndex200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPuzzleWebV2UserEventsControllerIndex200Response() *PuzzleWebV2UserEventsControllerIndex200Response {
	this := PuzzleWebV2UserEventsControllerIndex200Response{}
	return &this
}

// NewPuzzleWebV2UserEventsControllerIndex200ResponseWithDefaults instantiates a new PuzzleWebV2UserEventsControllerIndex200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPuzzleWebV2UserEventsControllerIndex200ResponseWithDefaults() *PuzzleWebV2UserEventsControllerIndex200Response {
	this := PuzzleWebV2UserEventsControllerIndex200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PuzzleWebV2UserEventsControllerIndex200Response) GetData() []Event {
	if o == nil || IsNil(o.Data) {
		var ret []Event
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PuzzleWebV2UserEventsControllerIndex200Response) GetDataOk() ([]Event, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PuzzleWebV2UserEventsControllerIndex200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Event and assigns it to the Data field.
func (o *PuzzleWebV2UserEventsControllerIndex200Response) SetData(v []Event) {
	o.Data = v
}

func (o PuzzleWebV2UserEventsControllerIndex200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PuzzleWebV2UserEventsControllerIndex200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullablePuzzleWebV2UserEventsControllerIndex200Response struct {
	value *PuzzleWebV2UserEventsControllerIndex200Response
	isSet bool
}

func (v NullablePuzzleWebV2UserEventsControllerIndex200Response) Get() *PuzzleWebV2UserEventsControllerIndex200Response {
	return v.value
}

func (v *NullablePuzzleWebV2UserEventsControllerIndex200Response) Set(val *PuzzleWebV2UserEventsControllerIndex200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePuzzleWebV2UserEventsControllerIndex200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePuzzleWebV2UserEventsControllerIndex200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePuzzleWebV2UserEventsControllerIndex200Response(val *PuzzleWebV2UserEventsControllerIndex200Response) *NullablePuzzleWebV2UserEventsControllerIndex200Response {
	return &NullablePuzzleWebV2UserEventsControllerIndex200Response{value: val, isSet: true}
}

func (v NullablePuzzleWebV2UserEventsControllerIndex200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePuzzleWebV2UserEventsControllerIndex200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


