/*
User Management API

API documentation for the User Management API a.k.a uman

API version: 1.0
Contact: api-support@fanscontest.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package platform

import (
	"encoding/json"
)

// checks if the HandlerGroupWinners type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlerGroupWinners{}

// HandlerGroupWinners struct for HandlerGroupWinners
type HandlerGroupWinners struct {
	GroupName *string `json:"group_name,omitempty"`
	Winners []HandlerWinner `json:"winners,omitempty"`
}

// NewHandlerGroupWinners instantiates a new HandlerGroupWinners object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlerGroupWinners() *HandlerGroupWinners {
	this := HandlerGroupWinners{}
	return &this
}

// NewHandlerGroupWinnersWithDefaults instantiates a new HandlerGroupWinners object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlerGroupWinnersWithDefaults() *HandlerGroupWinners {
	this := HandlerGroupWinners{}
	return &this
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *HandlerGroupWinners) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerGroupWinners) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *HandlerGroupWinners) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *HandlerGroupWinners) SetGroupName(v string) {
	o.GroupName = &v
}

// GetWinners returns the Winners field value if set, zero value otherwise.
func (o *HandlerGroupWinners) GetWinners() []HandlerWinner {
	if o == nil || IsNil(o.Winners) {
		var ret []HandlerWinner
		return ret
	}
	return o.Winners
}

// GetWinnersOk returns a tuple with the Winners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlerGroupWinners) GetWinnersOk() ([]HandlerWinner, bool) {
	if o == nil || IsNil(o.Winners) {
		return nil, false
	}
	return o.Winners, true
}

// HasWinners returns a boolean if a field has been set.
func (o *HandlerGroupWinners) HasWinners() bool {
	if o != nil && !IsNil(o.Winners) {
		return true
	}

	return false
}

// SetWinners gets a reference to the given []HandlerWinner and assigns it to the Winners field.
func (o *HandlerGroupWinners) SetWinners(v []HandlerWinner) {
	o.Winners = v
}

func (o HandlerGroupWinners) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlerGroupWinners) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupName) {
		toSerialize["group_name"] = o.GroupName
	}
	if !IsNil(o.Winners) {
		toSerialize["winners"] = o.Winners
	}
	return toSerialize, nil
}

type NullableHandlerGroupWinners struct {
	value *HandlerGroupWinners
	isSet bool
}

func (v NullableHandlerGroupWinners) Get() *HandlerGroupWinners {
	return v.value
}

func (v *NullableHandlerGroupWinners) Set(val *HandlerGroupWinners) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlerGroupWinners) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlerGroupWinners) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlerGroupWinners(val *HandlerGroupWinners) *NullableHandlerGroupWinners {
	return &NullableHandlerGroupWinners{value: val, isSet: true}
}

func (v NullableHandlerGroupWinners) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlerGroupWinners) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


